<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rick Rejeleene">
<meta name="dcterms.date" content="2025-09-14">
<meta name="description" content="Financial and Engineering of Window ACs">

<title>Reverse-Engineering Window AC: A Teardown and Cost Analysis – Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5d4d40b207192aa1b68a9430a7284735.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="http://rickrejeleene.me/"> <i class="bi bi-house-door-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://facebook.com/whitekangaroo"> <i class="bi bi-facebook" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/rick1776/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#how-a-window-ac-works" id="toc-how-a-window-ac-works" class="nav-link active" data-scroll-target="#how-a-window-ac-works"><span class="header-section-number">1</span> How a Window AC works?&nbsp;</a></li>
  <li><a href="#engineering-the-know-how" id="toc-engineering-the-know-how" class="nav-link" data-scroll-target="#engineering-the-know-how"><span class="header-section-number">2</span> Engineering the know-how</a>
  <ul class="collapse">
  <li><a href="#the-front-and-back-of-the-window-ac" id="toc-the-front-and-back-of-the-window-ac" class="nav-link" data-scroll-target="#the-front-and-back-of-the-window-ac"><span class="header-section-number">2.1</span> The Front and Back of the Window AC</a></li>
  <li><a href="#protection-case-for-window-ac" id="toc-protection-case-for-window-ac" class="nav-link" data-scroll-target="#protection-case-for-window-ac"><span class="header-section-number">2.2</span> Protection &amp; Case for Window AC</a></li>
  <li><a href="#unboxing-the-window-ac" id="toc-unboxing-the-window-ac" class="nav-link" data-scroll-target="#unboxing-the-window-ac"><span class="header-section-number">2.3</span> Unboxing the Window-AC:</a></li>
  <li><a href="#front-led-display-of-window-ac-and-evaporator-coil" id="toc-front-led-display-of-window-ac-and-evaporator-coil" class="nav-link" data-scroll-target="#front-led-display-of-window-ac-and-evaporator-coil"><span class="header-section-number">2.4</span> FRONT LED Display of Window AC and Evaporator Coil</a></li>
  </ul></li>
  <li><a href="#what-are-the-components-of-the-window-ac" id="toc-what-are-the-components-of-the-window-ac" class="nav-link" data-scroll-target="#what-are-the-components-of-the-window-ac"><span class="header-section-number">3</span> What are the components of the Window AC?</a>
  <ul class="collapse">
  <li><a href="#the-core-components-of-the-window-ac" id="toc-the-core-components-of-the-window-ac" class="nav-link" data-scroll-target="#the-core-components-of-the-window-ac"><span class="header-section-number">3.1</span> The Core Components of the Window-AC:</a></li>
  </ul></li>
  <li><a href="#tear-down-of-the-window-ac" id="toc-tear-down-of-the-window-ac" class="nav-link" data-scroll-target="#tear-down-of-the-window-ac"><span class="header-section-number">4</span> Tear down of the Window-AC</a>
  <ul class="collapse">
  <li><a href="#run-capacitor" id="toc-run-capacitor" class="nav-link" data-scroll-target="#run-capacitor"><span class="header-section-number">4.1</span> Run capacitor</a></li>
  <li><a href="#step-down-transformer" id="toc-step-down-transformer" class="nav-link" data-scroll-target="#step-down-transformer"><span class="header-section-number">4.2</span> Step-down Transformer</a></li>
  <li><a href="#power-plug-of-window-ac" id="toc-power-plug-of-window-ac" class="nav-link" data-scroll-target="#power-plug-of-window-ac"><span class="header-section-number">4.3</span> Power-Plug of Window-AC</a></li>
  <li><a href="#printed-circuit-board---pcb" id="toc-printed-circuit-board---pcb" class="nav-link" data-scroll-target="#printed-circuit-board---pcb"><span class="header-section-number">4.14</span> Printed Circuit Board - (PCB)</a>
  <ul class="collapse">
  <li><a href="#user-interface-pcb" id="toc-user-interface-pcb" class="nav-link" data-scroll-target="#user-interface-pcb">User Interface PCB</a></li>
  </ul></li>
  <li><a href="#front-pcb" id="toc-front-pcb" class="nav-link" data-scroll-target="#front-pcb"><span class="header-section-number">4.15</span> Front PCB</a>
  <ul class="collapse">
  <li><a href="#wiring-colors-you-see" id="toc-wiring-colors-you-see" class="nav-link" data-scroll-target="#wiring-colors-you-see">Wiring Colors You See</a></li>
  <li><a href="#why-colors" id="toc-why-colors" class="nav-link" data-scroll-target="#why-colors">Why Colors?</a></li>
  </ul></li>
  <li><a href="#thermistor" id="toc-thermistor" class="nav-link" data-scroll-target="#thermistor"><span class="header-section-number">4.16</span> Thermistor</a></li>
  <li><a href="#functional-analysis" id="toc-functional-analysis" class="nav-link" data-scroll-target="#functional-analysis"><span class="header-section-number">4.17</span> Functional Analysis:</a></li>
  <li><a href="#finding-the-components-for-the-window-ac-in-current-market" id="toc-finding-the-components-for-the-window-ac-in-current-market" class="nav-link" data-scroll-target="#finding-the-components-for-the-window-ac-in-current-market"><span class="header-section-number">4.18</span> Finding the Components for the Window-AC in Current Market</a></li>
  <li><a href="#how-are-they-assembled-and-put-together" id="toc-how-are-they-assembled-and-put-together" class="nav-link" data-scroll-target="#how-are-they-assembled-and-put-together"><span class="header-section-number">4.19</span> How are they Assembled and put together?</a></li>
  <li><a href="#core-system-components" id="toc-core-system-components" class="nav-link" data-scroll-target="#core-system-components"><span class="header-section-number">4.20</span> Core System Components</a></li>
  <li><a href="#internal-assembly-flow-diagram" id="toc-internal-assembly-flow-diagram" class="nav-link" data-scroll-target="#internal-assembly-flow-diagram"><span class="header-section-number">4.21</span> Internal Assembly – Flow Diagram</a></li>
  <li><a href="#window-air-conditioner-assembly-steps" id="toc-window-air-conditioner-assembly-steps" class="nav-link" data-scroll-target="#window-air-conditioner-assembly-steps"><span class="header-section-number">4.22</span> Window Air Conditioner Assembly Steps</a></li>
  <li><a href="#key-components-and-design-rationale" id="toc-key-components-and-design-rationale" class="nav-link" data-scroll-target="#key-components-and-design-rationale"><span class="header-section-number">4.23</span> Key Components and Design Rationale</a></li>
  </ul></li>
  <li><a href="#how-theyre-assembled-in-factory" id="toc-how-theyre-assembled-in-factory" class="nav-link" data-scroll-target="#how-theyre-assembled-in-factory"><span class="header-section-number">5</span> How they’re assembled in Factory?</a>
  <ul class="collapse">
  <li><a href="#line-stages" id="toc-line-stages" class="nav-link" data-scroll-target="#line-stages"><span class="header-section-number">5.1</span> Line Stages</a>
  <ul class="collapse">
  <li><a href="#cabinet-line" id="toc-cabinet-line" class="nav-link" data-scroll-target="#cabinet-line">Cabinet Line</a></li>
  <li><a href="#coil-line" id="toc-coil-line" class="nav-link" data-scroll-target="#coil-line">Coil Line</a></li>
  <li><a href="#base-assembly" id="toc-base-assembly" class="nav-link" data-scroll-target="#base-assembly">Base Assembly</a></li>
  <li><a href="#piping-metering" id="toc-piping-metering" class="nav-link" data-scroll-target="#piping-metering">Piping &amp; Metering</a></li>
  <li><a href="#electricals" id="toc-electricals" class="nav-link" data-scroll-target="#electricals">Electricals</a></li>
  <li><a href="#vacuum-charging" id="toc-vacuum-charging" class="nav-link" data-scroll-target="#vacuum-charging">Vacuum &amp; Charging</a></li>
  <li><a href="#end-of-line-qc" id="toc-end-of-line-qc" class="nav-link" data-scroll-target="#end-of-line-qc">End-of-Line QC</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#financial-costs-of-parts-in-window-ac" id="toc-financial-costs-of-parts-in-window-ac" class="nav-link" data-scroll-target="#financial-costs-of-parts-in-window-ac"><span class="header-section-number">6</span> Financial Costs of Parts in Window-AC</a>
  <ul class="collapse">
  <li><a href="#cost-estimation" id="toc-cost-estimation" class="nav-link" data-scroll-target="#cost-estimation"><span class="header-section-number">6.1</span> Cost Estimation</a></li>
  <li><a href="#typical-rehabilitation-bill-of-materials" id="toc-typical-rehabilitation-bill-of-materials" class="nav-link" data-scroll-target="#typical-rehabilitation-bill-of-materials"><span class="header-section-number">6.2</span> Typical Rehabilitation Bill of Materials</a></li>
  <li><a href="#fire-and-electrical-safety" id="toc-fire-and-electrical-safety" class="nav-link" data-scroll-target="#fire-and-electrical-safety"><span class="header-section-number">6.3</span> Fire and Electrical Safety</a></li>
  <li><a href="#regulatory-compliance" id="toc-regulatory-compliance" class="nav-link" data-scroll-target="#regulatory-compliance"><span class="header-section-number">6.4</span> Regulatory Compliance</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<!-- subscribe.html -->
<!-- Mailchimp CSS for styling -->
<link href="https://cdn-images.mailchimp.com/embedcode/classic-061523.css" rel="stylesheet" type="text/css">

<style type="text/css">
  #mc_embed_signup {
    background: #fff;
    font: 14px Helvetica, Arial, sans-serif;
    max-width: 400px;
    margin: 0 auto;
  }
</style>

<div id="mc_embed_signup">
  <form action="https://gmail.us12.list-manage.com/subscribe/post?u=1f588641ad0b06cbeecabd12b&amp;id=ca6e7ad445&amp;f_id=0028c0e1f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
    <div id="mc_embed_signup_scroll">
      <h2>Subscribe</h2>
      <div class="indicates-required">
        <span class="asterisk">*</span> indicates required
      </div>
      <div class="mc-field-group">
        <label for="mce-EMAIL">
          Email Address <span class="asterisk">*</span>
        </label>
        <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" required="">
      </div>

      <div id="mce-responses" class="clear foot">
        <div class="response" id="mce-error-response" style="display:none"></div>
        <div class="response" id="mce-success-response" style="display:none"></div>
      </div>

      <!-- honeypot field (bot protection) -->
      <div style="position: absolute; left: -5000px;" aria-hidden="true">
        <input type="text" name="b_1f588641ad0b06cbeecabd12b_ca6e7ad445" tabindex="-1" value="">
      </div>

      <div class="clear foot">
        <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe">
      </div>
    </div>
  </form>
</div>

<!-- Required Scripts -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js" type="text/javascript"></script>
<script type="text/javascript">
  (function ($) {
    window.fnames = new Array();
    window.ftypes = new Array();
    fnames[0] = "EMAIL";
    ftypes[0] = "email";
    fnames[1] = "FNAME";
    ftypes[1] = "text";
    fnames[2] = "LNAME";
    ftypes[2] = "text";
    fnames[3] = "ADDRESS";
    ftypes[3] = "address";
    fnames[4] = "PHONE";
    ftypes[4] = "phone";
    fnames[5] = "BIRTHDAY";
    ftypes[5] = "birthday";
    fnames[6] = "COMPANY";
    ftypes[6] = "text";
  })(jQuery);
  var $mcj = jQuery.noConflict(true);
</script>

</div></div>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Reverse-Engineering Window AC: A Teardown and Cost Analysis</h1>
<p class="subtitle lead">Manufacturing &amp; Engineering of Window ACs</p>
  <div class="quarto-categories">
    <div class="quarto-category">Economics</div>
    <div class="quarto-category">Manufacturing</div>
    <div class="quarto-category">Tamil Nadu</div>
    <div class="quarto-category">Engineering</div>
  </div>
  </div>

<div>
  <div class="description">
    Financial and Engineering of Window ACs
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rick Rejeleene </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 14, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="how-a-window-ac-works" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> How a Window AC works?&nbsp;</h1>
<blockquote class="blockquote">
<p>by Rick Rejeleene</p>
</blockquote>
<p>In Previous work, We explored the theoretical foundation of Air-conditioners.</p>
<p>We covered this in our previous article: <a href="https://rickrejeleene.me/Tamil/posts/2025-07-15-Airconditioners/index.html">How Air-conditioners work</a></p>
<p>In that post, it was mostly covering the theoretical side, which is required to understand. We used example of Voltas Split-AC, went through basics, including Firmware and PCB board.</p>
<p>In this article, we’ll delve into the practical know-how of simple window air conditioners.</p>
<p><strong>So, Why choose a Window AC?</strong></p>
<p>Firstly, It’s an inexpensive unit that has allowed mass manufacturing and scaling of cooling systems across the Globe. Secondly, our theoretical understanding can be now connected to practical, application-oriented understanding, which is why. Thirdly, what if we were able to scale cooling systems at mass, provide inexpensive systems to all socio-economic classes.</p>
<p>We have a Window AC unit, they are available everywhere, including India and America. Window-AC transformed the way, people lived in warm, hot places, providing comfort.<br>
If you were to walk to any towns in US, pass through restaurants, apartment buildings, you’d find the units.</p>
<p>The Goal of this post would be to understand everything deeply, so eventually, We can build a working prototype for ourselves. So this would involve tear down of an actual Window-AC. And then, We will do cost analysis. In the future post, We’d actually build and demonstrate a working prototype, Megan-1</p>
<p>An image of a Window-AC.</p>
<p><img src="../../images/Airconditioner/38.jpeg" class="img-fluid" style="width:99.0%"></p>
<p><strong>We’d focus on Finances and actual Engineering know-how</strong></p>
</section>
<section id="engineering-the-know-how" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Engineering the know-how</h1>
<p>This is the direction, we’d be following. So, our teardown would involve from electrical plug, front PCB board, capacitor. Next, main-PCB board, wiring involved and color codes, compressors, blower fan, evaporator coil.</p>
<section id="the-front-and-back-of-the-window-ac" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="the-front-and-back-of-the-window-ac"><span class="header-section-number">2.1</span> The Front and Back of the Window AC</h2>
<p><img src="../../images/Airconditioner/36.jpeg" class="img-fluid" style="width:99.0%"> <img src="../../images/Airconditioner/37.jpeg" class="img-fluid" style="width:99.0%"></p>
</section>
<section id="protection-case-for-window-ac" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="protection-case-for-window-ac"><span class="header-section-number">2.2</span> Protection &amp; Case for Window AC</h2>
<p>In the Window-AC, the way the covers are kept is both the indoor and outdoor units clamp together. There’s Outer Case, Inner Case. There’s vents, Drain holes. The inner frame is chasis.</p>
<p><strong>Outer Covering of the Window AC</strong></p>
<p><img src="../../images/Airconditioner/25.png" style="width:39.0%;height:40.0%"></p>
<p><strong>Outer cover and Evaporator Coil of the AC</strong></p>
<p><img src="../../images/Airconditioner/26.png" style="width:39.0%;height:40.0%"></p>
<p><img src="../../images/Airconditioner/27.png" style="width:39.0%;height:40.0%"></p>
</section>
<section id="unboxing-the-window-ac" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="unboxing-the-window-ac"><span class="header-section-number">2.3</span> Unboxing the Window-AC:</h2>
<p><img src="../../images/Airconditioner/24.jpeg" class="img-fluid" width="420"></p>
</section>
<section id="front-led-display-of-window-ac-and-evaporator-coil" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="front-led-display-of-window-ac-and-evaporator-coil"><span class="header-section-number">2.4</span> FRONT LED Display of Window AC and Evaporator Coil</h2>
<p>This is interesting, you can notice evaporator coil.</p>
<p><img src="../../images/Airconditioner/28.png" class="img-fluid" width="420"></p>
<p>This display is part of the control panel, which is often integrated with the unit’s thermostat. The LED screen typically shows the current room temperature, the desired set temperature, and the selected operating mode (e.g., Cool, Fan, Dry). It may also show fan speed, a timer setting, or other features.</p>
<p>This visual interface allows you to easily adjust the unit’s settings to your comfort, providing a more precise and convenient way to manage your indoor climate compared to older models with manual dials.</p>
</section>
</section>
<section id="what-are-the-components-of-the-window-ac" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> What are the components of the Window AC?</h1>
<p>Let’s go details into the core know-how of Window-AC</p>
<section id="the-core-components-of-the-window-ac" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="the-core-components-of-the-window-ac"><span class="header-section-number">3.1</span> The Core Components of the Window-AC:</h2>
<ol type="1">
<li>Compressor<br>
</li>
<li>Condenser Coil<br>
</li>
<li>Capillary Tube<br>
</li>
<li>Evaporator Coil<br>
</li>
<li>Blower Fan<br>
</li>
<li>Condenser Fan</li>
</ol>
</section>
</section>
<section id="tear-down-of-the-window-ac" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Tear down of the Window-AC</h1>
<section id="run-capacitor" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="run-capacitor"><span class="header-section-number">4.1</span> Run capacitor</h2>
<p><img src="../../images/Airconditioner/6.jpeg" class="img-fluid" width="420"></p>
<p>This is a dual-run capacitor. You might wonder, what does this do?</p>
<p>Let’s go with the basics. In electrical engineering, a capacitor is a device that stores electrical energy by accumulating electric charges on two closely spaced surfaces that are insulated from each other. Capacitors, together with resistors and inductors, belong to the group of passive components in electronic equipment.</p>
<p>Larger capacitors are used for energy storage in such applications as strobe lights, as parts of some types of electric motors, or for power factor correction in AC power distribution systems. Standard capacitors have a fixed value of capacitance, but adjustable capacitors are frequently used in tuned circuits. Different types are used depending on required capacitance, working voltage, current handling capacity, and other properties.</p>
<p>In our Window-AC, Capacitors act like a small battery, storing electrical energy and releasing it to help the compressor and fan motors start and run smoothly. Window units can have a single capacitor or a dual capacitor that serves both the fan and compressor.</p>
<p>This is found in HVAC systems as Heat Pumps. It’s primary job is to have two seperate capacitors with one casing, to provide continuous power to both fan and compressor motor. It has, two different microfarad (μF) ratings, one for each motor, and three terminals: a common terminal for the power supply, a “herm” terminal for the compressor, and a “fan” terminal for the fan motor. This “two-in-one” design saves space and cost compared to using two individual capacitors.</p>
</section>
<section id="step-down-transformer" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="step-down-transformer"><span class="header-section-number">4.2</span> Step-down Transformer</h2>
<p>This is an interesting part, so after reading the books and understanding the theory. It’s time to open it up and see how it works. I was surprised by this part. Rest of the components seem expected as it’s part of the Refrigerant Cycle.</p>
<p>In the Window-AC, we find there’s Step down Transformer. It’s also called as control transformer. The main role of this transformer is to take AC power and then convert it into lower AC-power.</p>
<p><img src="../../images/Airconditioner/step_down_transformer.png" style="width:39.0%;height:40.0%"></p>
<p>Input: ~120V or 220V AC</p>
<p>Output: 12V–35V AC</p>
<p>So, we notice there’s two set of wiring and we might wonder, Why do we need two sets of wiring? The reason is because, there’s two windings, as part of the Magnetic Cores, within the Step-down transformers.</p>
</section>
<section id="power-plug-of-window-ac" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="power-plug-of-window-ac"><span class="header-section-number">4.3</span> Power-Plug of Window-AC</h2>
<p>This is standard North American plug. In India, sockets are not the same.</p>
<p>North American sockets, plugs are named through NEMA (National Electrical Manufacturers Association). It’s 120 V and 60 Hz.</p>
<p>So, We have Type A: NEMA 1-15 (two flat parallel blades, ungrounded) Next, We have Type B: NEMA 5-15 (two flat parallel blades with a round grounding pin)</p>
<p>India’s electric system is typically 230 V and 50 Hz. We have, the following: Type C: Europlug (two round pins) Type D: BS 546 standard (three round pins in a triangular pattern, 5 amps) Type M: Larger version of Type D (three round pins in a triangular pattern, 15 amps)</p>
<p><img src="../../images/Airconditioner/1.jpeg" style="width:39.0%;height:40.0%"></p>
<p><img src="../../images/Airconditioner/2.jpeg" style="width:39.0%;height:40.0%"></p>
</section>
<div class="quarto-layout-panel" data-layout-ncol="1">
<div class="quarto-layout-row">
<section id="pcb-board-control-unit" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="pcb-board-control-unit"><span class="header-section-number">4.4</span> PCB Board: Control Unit</h2>
<p>This Printed Circuit Board is specifically designed to function as a controller. In short, it manages functions, information, and provides reliability.</p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>The easiest one to recognize in the PCB board is the fuse. It protects the PCB board from overcurrent or short-currents. If you were to play with a Mutlimeter, you’d test out continuity through checking the fuse first.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>This is where, handling fan control, temperature sensing, compressor relay control, and communication with the remote/display unit takes place. In previous post, we went deeper into how progamming is executed through showing examples from embedded systems.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="../../images/Airconditioner/7.jpeg" class="img-fluid" width="420"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<ol type="1">
<li>Red, blue, yellow wires are Signal and power wires going to fan motor, sensors, compressor</li>
<li>White connectors are interface headers connecting display, thermistors, IR receivers</li>
</ol>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p><strong>Microcontrollers</strong> We have a black IC, 8 pin and 20-pin IC. Actually I was wondering, why you have two? My answer was probably a design choice. So both of them are involved in Thermistor inputs, Relay switching, Mode selection, Timer logic, IR remote decoding.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>We have Electromagnetic relays that are in two black rectangular components. One is for fan motor, and another is for compressor control.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>Several black rectangular boxes of different sizes These are switches that turn high-power equipment on/off (compressor, fan motors, heating elements) The control board sends low-voltage signals to these, which then switch high-voltage power Red and black thick wires are carring AC line voltage to the compressor/fan via relays The Gray metal fins are voltage regulator, with heat sink to provide 5V DC.</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="compressor" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="compressor"><span class="header-section-number">4.5</span> Compressor</h2>
<p>The heart of the Airconditioner.</p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="../../images/Airconditioner/10.png" class="img-fluid"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>There are many types of Compressor.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>The one, in the picture is Rotary Compressor. Compressor is the most expensive unit for the Window-AC. The reason is complexity and making it into production. Inside the Rotary Compressor is the precision pump and an electric motor inside a welded, hermetic shell.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>It draws in low-pressure, slightly superheated refrigerant vapor at the suction port and compresses it to a high-pressure, high-temperature gas. That hot gas flows to the condenser coil, where a fan removes heat and the gas condenses into a high-pressure liquid.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>The liquid then passes through the capillary/expansion device, where its pressure drops; inside the evaporator coil it boils and absorbs heat from the room air. Inside a rotary compressor you’ll find an electric motor, eccentric shaft with rolling piston, spring-loaded vane, suction/discharge reed valves, bearings, and oil sump/pump for lubrication and motor cooling.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>As an Engineer, I believe advances in this would help to reduce cost and increase effiency. The reason is two fold, for cost this is the most expensive unit, for power-consumption, this is what consumes the most power. So, this is where innovation, improvements ought to be made for HVAC systems. This is not to say, other components are not important. There’s an entire specialization, area for compressors in Mechanical Engineering.</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="wiring-to-the-pcb-board-and-capacitor" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="wiring-to-the-pcb-board-and-capacitor"><span class="header-section-number">4.6</span> Wiring to the PCB Board and Capacitor</h2>
<p>HVAC follows standard colors, not all appliances would follow the standards. This might be different for India, China and U.S. For now, we explain basics in US for wiring.</p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>Green - Safety White/Blue - Neutral Black/Brown - Line/Hot (L) Red / Yellow / Blue - Motor Leads, usually fan speeds, compressor, capacitor links.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="../../images/Airconditioner/13.jpeg" class="img-fluid" width="400"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>We can notice the Capacitor placed within the PCB board. In our Window-AC, The capacitor creates a phase shift in the current, providing the necessary torque for the motors to start and run efficiently. It acts like a starter muscle for the compressor and fan motors.</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="pcb-board-wiring" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="pcb-board-wiring"><span class="header-section-number">4.7</span> PCB Board Wiring</h2>
<p><img src="../../images/Airconditioner/16.jpeg" class="img-fluid" width="420"></p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>There’s two PCB board, one is the front-end, this one is the main PCB board.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>Primarily to regulate, control, distribute power. System control involves turning on, off, change temperature, fan speed, operational modes. These are standard in Window-AC. If we are to introduce newer features, we would be working on this.</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="front-pcb-board" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="front-pcb-board"><span class="header-section-number">4.8</span> Front PCB Board</h2>
<p><img src="../../images/Airconditioner/18.jpeg" class="img-fluid" width="420"></p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>This one is connected to the Front LED Display panel. So, I went through the front PCB board. It’s a low-voltage logic board. It’s powered by the step-down transformer, it has buttons, LEDs, 7-segment display, microcontroller I/O lines. It also has relays signals to the main power/control board via the white connector on the right.</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="blower-wheel" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="blower-wheel"><span class="header-section-number">4.9</span> Blower Wheel</h2>
<p><img src="../../images/Airconditioner/20.jpeg" class="img-fluid" width="420"></p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>This is a blower wheel present in the Window-AC. A blower wheel is an impeller that spins to create airflow, circulating air in systems It’s used to create airflow. And if you are wondering, what’s an impeller?</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>It’s a flow device, typically with helically shaped blades, that rotates to create fluid movement, primarily in low-viscosity liquids.</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="condenser-coil" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="condenser-coil"><span class="header-section-number">4.10</span> Condenser coil</h2>
<p>The condenser coil is the “hot” side of the air conditioner, located on the exterior half of the unit that faces outside.</p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="../../images/Airconditioner/21.jpeg" class="img-fluid" width="420"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>Its primary function is to release heat. After the refrigerant absorbs heat from inside the room at the evaporator coil, it is compressed, becoming a hot, high-pressure gas. This hot refrigerant then travels to the condenser coil.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="../../images/Airconditioner/22_png.png" class="img-fluid" width="420"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="../../images/Airconditioner/23.png" class="img-fluid" width="420"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>As the fan blows outdoor air over the condenser fins, the heat from the refrigerant is transferred to the outside air, and the refrigerant cools and turns back into a liquid.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>In contrast, the evaporator coil is the “cold” side, located on the inside, and its function is to absorb heat. Both coils are essential for the refrigeration cycle, but they perform opposite, equally important, tasks.</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="corner-parts-of-evaporator-coil" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="corner-parts-of-evaporator-coil"><span class="header-section-number">4.11</span> Corner parts of Evaporator Coil</h2>
<p><img src="../../images/Airconditioner/40.jpeg" class="img-fluid" width="420"> <img src="../../images/Airconditioner/41.jpeg" class="img-fluid" width="420"></p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>The evaporator coil is a critical component of any air conditioning system. We can see its located on the indoor side of the unit and is responsible for absorbing heat from the air inside the room. The evaporator coil is typically made of copper or aluminum tubing bent into a serpentine shape, with thin metal fins attached to increase the surface area.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>The refrigerant, a special fluid that easily changes from liquid to gas and back, flows through these tubes. As warm, humid air from the room is blown across the cold coil, the refrigerant absorbs the heat and evaporates into a gas. This cools and dehumidifies the air, which is then blown back into the room</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="compressor-evaporator-coil" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;" data-number="4.12">
<h2 data-number="4.12" class="anchored" data-anchor-id="compressor-evaporator-coil"><span class="header-section-number">4.12</span> Compressor &amp; Evaporator Coil:</h2>
<p><img src="../../images/Airconditioner/32.png" class="img-fluid" width="420"></p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>The Evaporator Coil, we notice blue-colored coating. This encourages condensed water to spread across the fins instead of forming droplets, which improves heat transfer efficiency, speeds up cooling, prevents airflow obstruction, and protects against corrosion and rust. The refrigerant comes from the compressor, cycles continuously.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>There’s capillary tube and a larger tube within the evaporator coil. It’s main goals are absorb heat from the air, and send that heat away through the refrigerant.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>The compressor, fan, and PCB (Printed Circuit Board) board work together in a coordinated cycle to cool a room. The compressor is the “engine” of the refrigeration cycle. It receives the cool, low-pressure gaseous refrigerant from the evaporator coil, compresses it to a high-pressure, high-temperature gas, and then pumps it to the condenser coil on the outside of the unit. The fan serves two critical purposes: the indoor fan blows warm room air over the evaporator coil to be cooled, while the outdoor fan blows outside air over the hot condenser coil to help it release heat.</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>The PCB board is the “brain” of the entire operation. It receives signals from the thermostat, controls the compressor and fan motors, and manages the unit’s settings to maintain the desired temperature. All these parts work together in a continuous loop to remove heat from the indoor air and release it outside, providing a comfortable living space.</p>
</div>
</div>
<div class="quarto-layout-row">
<section id="components-in-the-opened-window-ac" class="level2 quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;" data-number="4.13">
<h2 data-number="4.13" class="anchored" data-anchor-id="components-in-the-opened-window-ac"><span class="header-section-number">4.13</span> Components in the Opened Window-AC</h2>
<p>Computer Vision algorithms are able to classify the torn down Window-AC. This is a template, sample from the classification.</p>
</section>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="../../images/Airconditioner/window_ac_marked.png" class="img-fluid" width="420"></p>
</div>
</div>
</div>
<section id="printed-circuit-board---pcb" class="level2" data-number="4.14">
<h2 data-number="4.14" class="anchored" data-anchor-id="printed-circuit-board---pcb"><span class="header-section-number">4.14</span> Printed Circuit Board - (PCB)</h2>
<section id="user-interface-pcb" class="level3">
<h3 class="anchored" data-anchor-id="user-interface-pcb">User Interface PCB</h3>
<p><img src="../../images/Airconditioner/4.jpeg" class="img-fluid" width="420"></p>
<p>We are seeing the solder side of PCB board.</p>
<p>This is the main control board inside your AC unit. It connects the front control panel (buttons, display, remote sensor) with the power section (compressor, fan motor, capacitor, sensors). Think of it as the middleman between you (the user) and the heavy electrical parts.</p>
<p>This board processes signals from sensors (thermistor/temperature, sometimes humidity). It controls relays/triacs that switch ON/OFF the compressor, blower fan, swing motor. It regulates fan speeds (low, med, high) by sending different voltages to the fan motor windings. It has a power supply section that converts 220V/110V AC into low DC (5V/12V) for the logic ICs and display. It also handles the remote-control receiver (infrared sensor).</p>
<p>So:You press a button → signal goes into microcontroller → PCB decides → relay clicks → compressor or fan gets power.</p>
</section>
</section>
<section id="front-pcb" class="level2" data-number="4.15">
<h2 data-number="4.15" class="anchored" data-anchor-id="front-pcb"><span class="header-section-number">4.15</span> Front PCB</h2>
<p><img src="../../images/Airconditioner/PCBfront.jpeg" class="img-fluid" style="width:99.0%"></p>
<section id="wiring-colors-you-see" class="level3">
<h3 class="anchored" data-anchor-id="wiring-colors-you-see">Wiring Colors You See</h3>
<ol type="1">
<li>Red wires: Typically 24V power supply (hot)</li>
<li>Blue wires: Often neutral or return power</li>
<li>Yellow wire: Usually compressor control signal</li>
<li>White wires: Common connections or sensor inputs</li>
<li>Green wires: Often fan control or ground connections</li>
<li>Orange/other colors: Various sensor inputs and control signals</li>
</ol>
</section>
<section id="why-colors" class="level3">
<h3 class="anchored" data-anchor-id="why-colors">Why Colors?</h3>
<p>Colors are conventions to avoid mistakes during service. 1. High-voltage (motor/compressor) wires are thicker and brightly colored (safety). 2. Signal/logic wires are thinner, often rainbow colors.</p>
</section>
</section>
<section id="thermistor" class="level2" data-number="4.16">
<h2 data-number="4.16" class="anchored" data-anchor-id="thermistor"><span class="header-section-number">4.16</span> Thermistor</h2>
<p>A thermistor is a specialized resistor. It measures the temperature of the evaporator coil or incoming air and sends this data (as a change in resistance) to the control board, which uses it to cycle the compressor on and off to maintain the set temperature.</p>
</section>
<section id="functional-analysis" class="level2" data-number="4.17">
<h2 data-number="4.17" class="anchored" data-anchor-id="functional-analysis"><span class="header-section-number">4.17</span> Functional Analysis:</h2>
<section id="electrical-schematic" class="level4">
<h4 class="anchored" data-anchor-id="electrical-schematic">Electrical schematic</h4>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
mains[AC Mains]--&gt;PSU[PSU 12V/5V]
mains--&gt;relay[Compressor Contactor/Relay]
PSU--&gt;MCU[Controller / Thermostat]
MCU--&gt;relay
MCU--&gt;if[Indoor Fan Speeds]
MCU--&gt;of[Outdoor Fan]
sens[Thermistors / HP-LP / Float switch]--&gt;MCU
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="air-flow-schematic" class="level4">
<h4 class="anchored" data-anchor-id="air-flow-schematic">Air-Flow Schematic</h4>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TB
RA[Return Air]--&gt;FX[Filter]
FX--&gt;EVA[Evaporator Coil]
EVA--&gt;IB[Indoor Blower]--&gt;SA[Supply Air]
OA[Outdoor Air]--&gt;CF[Condenser Fan]--&gt;CON[Condenser Coil]--&gt;DO[Discharge Outdoors]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
<section id="finding-the-components-for-the-window-ac-in-current-market" class="level2" data-number="4.18">
<h2 data-number="4.18" class="anchored" data-anchor-id="finding-the-components-for-the-window-ac-in-current-market"><span class="header-section-number">4.18</span> Finding the Components for the Window-AC in Current Market</h2>
<p>This is a Template on how to find the components for Window-AC. For components, lot of suppliers from China, India.This is obvious that components are cheaper in China and India.</p>
<div id="b3820378" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code> Component Pricing Comparison</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Component</th>
<th data-quarto-table-cell-role="th">China ($)</th>
<th data-quarto-table-cell-role="th">India ($)</th>
<th data-quarto-table-cell-role="th">USA ($)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Compressor (1/2 HP)</td>
<td>85</td>
<td>95</td>
<td>180</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Evaporator Coil</td>
<td>35</td>
<td>45</td>
<td>80</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Condenser Coil</td>
<td>40</td>
<td>50</td>
<td>85</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Condenser Fan Motor</td>
<td>25</td>
<td>35</td>
<td>65</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Evaporator Fan Motor</td>
<td>20</td>
<td>28</td>
<td>55</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Control Board/PCB</td>
<td>30</td>
<td>40</td>
<td>85</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Thermostat</td>
<td>15</td>
<td>22</td>
<td>45</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Capacitor (Start/Run)</td>
<td>8</td>
<td>12</td>
<td>25</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Window Installation Kit</td>
<td>12</td>
<td>18</td>
<td>35</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Refrigerant Lines</td>
<td>15</td>
<td>20</td>
<td>40</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Housing/Cabinet</td>
<td>60</td>
<td>75</td>
<td>150</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>Air Filter</td>
<td>5</td>
<td>8</td>
<td>15</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cost Summary by Market</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Market</th>
<th data-quarto-table-cell-role="th">Total Cost (USD)</th>
<th data-quarto-table-cell-role="th">Savings vs USA</th>
<th data-quarto-table-cell-role="th">Savings %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>🇨🇳 China</td>
<td>350</td>
<td>510</td>
<td>59.3%</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>🇮🇳 India</td>
<td>448</td>
<td>412</td>
<td>47.9%</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>🇺🇸 USA</td>
<td>860</td>
<td>0</td>
<td>0%</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Key Findings
Total Component Costs:
- 🇨🇳 China: $350
- 🇮🇳 India: $448
- 🇺🇸 USA: $860

Cost Savings Analysis:
- China vs USA: $510 (59.3% savings)
- India vs USA: $412 (47.9% savings)
Primary Suppliers by Region</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Region</th>
<th data-quarto-table-cell-role="th">Primary Suppliers</th>
<th data-quarto-table-cell-role="th">Key Links</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>🇨🇳 China</td>
<td>Made-in-China.com, Alibaba</td>
<td>https://airconditionersystem.en.made-in-china....</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>🇮🇳 India</td>
<td>IndiaMART, TradeIndia, Aldahome</td>
<td>https://dir.indiamart.com/impcat/air-condition...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>🇺🇸 USA</td>
<td>GE Appliance Parts, Repair Clinic, PartSelect</td>
<td>https://www.geapplianceparts.com/</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Window AC Assembly Process</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Process</th>
<th data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Cabinet Line</td>
<td>Sheet-metal stamping → welding → powder-coat →...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Coil Line</td>
<td>Fin press → copper hairpin bending → tube inse...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Base Assembly</td>
<td>Mount compressor on rubber grommets → fit cond...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Piping &amp; Metering</td>
<td>Braze discharge/suction → filter-drier → capil...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Electricals</td>
<td>Wiring harness → capacitor(s) → relay/overload...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Vacuum &amp; Charge</td>
<td>Pull to &lt;500 microns → hold → charge refrigera...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>End-of-Line Test</td>
<td>Run test for power draw → temps/pressures → so...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="how-are-they-assembled-and-put-together" class="level2" data-number="4.19">
<h2 data-number="4.19" class="anchored" data-anchor-id="how-are-they-assembled-and-put-together"><span class="header-section-number">4.19</span> How are they Assembled and put together?</h2>
<p>In this, pay close attention, while we can think of each and every part. I am reminded of Interchangeable Parts, American System of Manufacturing, that standardized manufacturing. The skilled specialized labor was replaced as Whitney’s system of manfacturing came into production. This allowed for mass production.</p>
<p>When machines get complex, we can think of sub-sections, sub-systems together. In this way, it’s easier to piece them together and test them out. While assembling is important phase, in global manufacturing system, it is complex. This is for majority of industry except defense sector, the parts, components all come from various locations. In large companies, they have contractors, suppliers who manage all this, and the assembling will take place in another location. All is decided based on company’s resources, goals, this apporach makes it efficient.</p>
</section>
<section id="core-system-components" class="level2" data-number="4.20">
<h2 data-number="4.20" class="anchored" data-anchor-id="core-system-components"><span class="header-section-number">4.20</span> Core System Components</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 36%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Subsystem</th>
<th>Components</th>
<th>Function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Refrigerant Loop</td>
<td>Compressor, Condenser Coil, Capillary Tube, Evaporator Coil</td>
<td>Transfers heat from indoors to outdoors via phase change.</td>
</tr>
<tr class="even">
<td>Air Circulation</td>
<td>Fan Motor, Dual-Shaft Fan, Blower Wheel, Condenser Fan</td>
<td>Moves air over evaporator (cool air) and condenser (heat exhaust).</td>
</tr>
<tr class="odd">
<td>Electrical Control</td>
<td>PCB, Capacitor, Transformer, Thermistor, Relay, IR sensor</td>
<td>Manages temperature control, motor startup, and user interface.</td>
</tr>
<tr class="even">
<td>Frame &amp; Housing</td>
<td>Sheet Metal Casing, Mounting Rails, Side Curtains, Filters</td>
<td>Provides structural integrity, mounting support, and airflow isolation.</td>
</tr>
</tbody>
</table>
<hr>
<p>Almost all the Airconditioners will come with instruction manual. In the manual, you’d have wiring diagram, frequently asked questions.</p>
</section>
<section id="internal-assembly-flow-diagram" class="level2" data-number="4.21">
<h2 data-number="4.21" class="anchored" data-anchor-id="internal-assembly-flow-diagram"><span class="header-section-number">4.21</span> Internal Assembly – Flow Diagram</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    Step1[Install Compressor]
    Step2[Mount Condenser Coil]
    Step3[Mount Evaporator Coil]
    Step4[Connect Capillary and Tubing]
    Step5[Vacuum and Refrigerant Charging]
    Step6[Install Dual Shaft Fan Motor]
    Step7[Attach Fan Blades and Ducts]
    Step8[Mount PCB and Transformer]
    Step9[Install Control Panel]
    Step10[Install Filter and Front Grille]
    Step11[Attach Rear Cover and Side Curtains]
    Step12[Final Testing and Packaging]

    Step1 --&gt; Step2 --&gt; Step3 --&gt; Step4 --&gt; Step5 --&gt; Step6 --&gt; Step7 --&gt; Step8 --&gt; Step9 --&gt; Step10 --&gt; Step11 --&gt; Step12

</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="window-air-conditioner-assembly-steps" class="level2" data-number="4.22">
<h2 data-number="4.22" class="anchored" data-anchor-id="window-air-conditioner-assembly-steps"><span class="header-section-number">4.22</span> Window Air Conditioner Assembly Steps</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 30%">
<col style="width: 16%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Subsystem</th>
<th>Task</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Refrigerant</td>
<td>Install Compressor</td>
<td>Mount rotary compressor inside the base with rubber dampers.</td>
</tr>
<tr class="even">
<td>2</td>
<td>Refrigerant</td>
<td>Mount Condenser Coil</td>
<td>Position condenser coil at the rear of the unit.</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Refrigerant</td>
<td>Mount Evaporator Coil</td>
<td>Place evaporator at the front behind the air outlet grille.</td>
</tr>
<tr class="even">
<td>4</td>
<td>Refrigerant</td>
<td>Connect Capillary Tubes</td>
<td>Braze tubes from condenser → capillary → evaporator → suction line.</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Refrigerant</td>
<td>Vacuum and Charge</td>
<td>Pull vacuum and inject refrigerant (R-32 or R-410A).</td>
</tr>
<tr class="even">
<td>6</td>
<td>Air Circulation</td>
<td>Install Fan Motor</td>
<td>Mount the dual-shaft motor between coils.</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Air Circulation</td>
<td>Attach Fan Blades</td>
<td>Attach blower wheel and condenser fan on both shafts.</td>
</tr>
<tr class="even">
<td>8</td>
<td>Electrical</td>
<td>Mount PCB and Transformer</td>
<td>Screw PCB onto bracket, connect transformer, relay, capacitor.</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Electrical</td>
<td>Install Control Panel</td>
<td>Add IR sensor, LED display, buttons, and connect to PCB.</td>
</tr>
<tr class="even">
<td>10</td>
<td>Frame</td>
<td>Install Filter and Grille</td>
<td>Insert air filter, snap in plastic grille.</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Frame</td>
<td>Attach Rear Cover</td>
<td>Fix back casing and side curtains.</td>
</tr>
<tr class="even">
<td>12</td>
<td>QA</td>
<td>Final Testing</td>
<td>Run cooling test, check airflow and water drainage.</td>
</tr>
</tbody>
</table>
</section>
<section id="key-components-and-design-rationale" class="level2" data-number="4.23">
<h2 data-number="4.23" class="anchored" data-anchor-id="key-components-and-design-rationale"><span class="header-section-number">4.23</span> Key Components and Design Rationale</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 39%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Component</th>
<th>Reason</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Compressor</td>
<td>Rotary Hermetic (GMCC)</td>
<td>Reliable, quiet, low energy consumption</td>
</tr>
<tr class="even">
<td>Coil Material</td>
<td>Copper Tube with Aluminum Fin</td>
<td>Heat-efficient, low cost</td>
</tr>
<tr class="odd">
<td>Expansion Device</td>
<td>Capillary Tube</td>
<td>Passive device, no moving parts</td>
</tr>
<tr class="even">
<td>Fan Motor</td>
<td>PSC Dual-Shaft Motor</td>
<td>Single motor runs both blower and condenser</td>
</tr>
<tr class="odd">
<td>PCB Voltage</td>
<td>Step-Down to 12–35V AC</td>
<td>Safety and standardization</td>
</tr>
<tr class="even">
<td>Frame</td>
<td>Galvanized Steel</td>
<td>Durable and rust-resistant</td>
</tr>
<tr class="odd">
<td>Assembly</td>
<td>Snap Fit + Screws</td>
<td>Mass-production ready</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="how-theyre-assembled-in-factory" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> How they’re assembled in Factory?</h1>
<p>Window AC manufacturing follows a modular, parallel line system, each major subsystem is prepared in <strong>separate sub-lines</strong>, then merged during final assembly. Below is the typical industrial line flow:</p>
<section id="line-stages" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="line-stages"><span class="header-section-number">5.1</span> Line Stages</h2>
<p>Most of the time, it’s divided, the work is parallelized. If you think from capital, sales point of view, you want to manufacture matching the demand. Toyota’s concepts of Lean manufacturing might be relevant here. They only make what you need, do not make, create any waste, which is impressive. From what I gather, they improvised from Ford’s factories, such should be anyone who is an industrialist.</p>
<section id="cabinet-line" class="level3">
<h3 class="anchored" data-anchor-id="cabinet-line">Cabinet Line</h3>
<ul>
<li>Sheet metal is <strong>stamped</strong>, <strong>punched</strong>, and <strong>notched</strong> into side panels, top/bottom trays, and baffles.</li>
<li>Edges are spot <strong>welded</strong> or folded with fasteners.</li>
<li>Assembly passes through <strong>powder coating booths</strong>, then a <strong>curing oven</strong> at ~200°C.</li>
</ul>
</section>
<section id="coil-line" class="level3">
<h3 class="anchored" data-anchor-id="coil-line">Coil Line</h3>
<ul>
<li><strong>Fin press</strong> stamps aluminum fins.</li>
<li><strong>Copper hairpins</strong> are bent and inserted into fin stacks.</li>
<li>Tubes are <strong>mechanically expanded</strong> to bond fin to copper.</li>
<li>All joints are <strong>brazed</strong> with nitrogen purge.</li>
<li><strong>Helium leak testing</strong> checks for micro-leaks.</li>
</ul>
</section>
<section id="base-assembly" class="level3">
<h3 class="anchored" data-anchor-id="base-assembly">Base Assembly</h3>
<ul>
<li>Compressor is mounted on <strong>rubber grommets</strong> on the chassis.</li>
<li><strong>Condenser and evaporator coils</strong> are fitted and aligned.</li>
<li><strong>Dual-shaft motor</strong>, blower wheel, and condenser fan are installed.</li>
<li><strong>Shrouds</strong> guide airflow and ensure sealing.</li>
</ul>
</section>
<section id="piping-metering" class="level3">
<h3 class="anchored" data-anchor-id="piping-metering">Piping &amp; Metering</h3>
<ul>
<li>Braze <strong>discharge</strong>, <strong>suction</strong>, and <strong>filter-drier</strong> connections.</li>
<li>Connect <strong>capillary tube → distributor → evaporator</strong>.</li>
<li>Add <strong>service stub</strong> for later vacuuming and charging.</li>
</ul>
</section>
<section id="electricals" class="level3">
<h3 class="anchored" data-anchor-id="electricals">Electricals</h3>
<ul>
<li>Add <strong>wiring harness</strong>, <strong>capacitors</strong>, and <strong>relay or overload protector</strong>.</li>
<li>Mount and wire <strong>control PCB</strong>, IR sensor, display.</li>
</ul>
</section>
<section id="vacuum-charging" class="level3">
<h3 class="anchored" data-anchor-id="vacuum-charging">Vacuum &amp; Charging</h3>
<ul>
<li>Pull system down to <strong>&lt; 500 microns</strong> using vacuum pump.</li>
<li>Hold vacuum for stability test.</li>
<li>Charge <strong>refrigerant by weight</strong> (e.g., 450g R-32).</li>
<li>Pinch, crimp, and seal service line.</li>
</ul>
</section>
<section id="end-of-line-qc" class="level3">
<h3 class="anchored" data-anchor-id="end-of-line-qc">End-of-Line QC</h3>
<ul>
<li>Run full test:
<ul>
<li><strong>Amps, pressures, noise, airflow, leak sniffing</strong>.</li>
</ul></li>
<li>Approve with <strong>QC stamp</strong>.</li>
<li>Pack with foam, box, manual → <strong>palletize</strong> for shipping.</li>
</ul>
<p>A Flow Diagram of the Assembling:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A[Cabinet Line]
    B[Coil Line]
    C[Base Assembly]
    D[Piping and Metering]
    E[Electrical Wiring]
    F[Vacuum and Charging]
    G[End-of-Line Testing]
    H[Packaging and Palletizing]

    A --&gt; C
    B --&gt; C
    C --&gt; D --&gt; E --&gt; F --&gt; G --&gt; H
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="financial-costs-of-parts-in-window-ac" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Financial Costs of Parts in Window-AC</h1>
<p>This is certainly the most challenging part, this applies to manufacturing or majority of the business. If you are CTO or Chief head that is manufacturing components, from manufacturing, business point of view, this is essential. If you could reduce the price of components by 50% that will increase your profits at the end. In broader chain of value-activities, this would be one component, yet this is process improvement. Historically, many industrialists have made wonders in this chain of value added activities, which pushed for effiency and thwart competitors. Andrew Carnegie hired a Chemist, Dr.&nbsp;Fricke, who figured out a way to manufacture pig iron cheaper.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../images/Airconditioner/Window_AC_Parts.png" class="img-fluid figure-img" title="Optional Title" alt="Alternative text"></p>
<figcaption>Breakdown of component costs</figcaption>
</figure>
</div>
<p>We can notice Evaporator Coil, Condensor Coil, Compressor occupies close to 80% of the costs. That is staggering 3/4th of the expenses of the unit. The reason why they are expensive is manufacturing complexity. Secondly, the materials used to make them also add to the cost. Also add labor, transportation costs.</p>
<p>We can notice how difficult it is to manage expenses, that itself requires tightly controlling accounting and balancing the budget. Expenses would add up easily and making the unit will turn into unprofitable venue for manufacturers.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Numbers vary by tonnage (here ~1 ton / 12k BTU), volume, region, and refrigerant. Use as planning ranges, not quotations.</p>
</div>
</div>
<div id="tbl-oem-retail" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-tbl-colwidths="[22,14,30,17,17]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-oem-retail-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Indicative costs (OEM vs.&nbsp;replacement retail)
</figcaption>
<div aria-describedby="tbl-oem-retail-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<caption>Indicative costs (OEM vs.&nbsp;replacement retail)</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 14%">
<col style="width: 30%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Subsystem / Part</th>
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Manufacturing &amp; materials notes</th>
<th style="text-align: left;">OEM cost (high-volume)</th>
<th style="text-align: left;">Replacement retail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rotary compressor (R-410A/R-32, ~12k BTU)</td>
<td style="text-align: left;">Pump refrigerant</td>
<td style="text-align: left;">Hermetic shell; precision rotor/vane; motor; oil; welded stubs</td>
<td style="text-align: left;">$90–$160</td>
<td style="text-align: left;">$230–$300</td>
</tr>
<tr class="even">
<td style="text-align: left;">Evaporator coil</td>
<td style="text-align: left;">Absorb indoor heat</td>
<td style="text-align: left;">Cu/Al tubes + louvered fins; leak-proof brazing; hydrophilic coat optional</td>
<td style="text-align: left;">$30–$90</td>
<td style="text-align: left;">$80–$180</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Condenser coil</td>
<td style="text-align: left;">Reject outdoor heat</td>
<td style="text-align: left;">Similar to evap; subcooling section; corrosion protection</td>
<td style="text-align: left;">$30–$90</td>
<td style="text-align: left;">$100–$170</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dual-shaft motor</td>
<td style="text-align: left;">Drive blower + condenser fan</td>
<td style="text-align: left;">Shaded-pole/PSC; multiple speed taps; rubber mounts</td>
<td style="text-align: left;">$25–$60</td>
<td style="text-align: left;">$180–$300</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Blower wheel (indoor)</td>
<td style="text-align: left;">Move indoor air</td>
<td style="text-align: left;">Injection-molded; balance critical</td>
<td style="text-align: left;">$8–$25</td>
<td style="text-align: left;">$60–$170</td>
</tr>
<tr class="even">
<td style="text-align: left;">Condenser fan blade</td>
<td style="text-align: left;">Move outdoor air</td>
<td style="text-align: left;">Stamped/plastic prop; pitch &amp; diameter tuned</td>
<td style="text-align: left;">$5–$15</td>
<td style="text-align: left;">$43–$107</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Control PCB + UI PCB</td>
<td style="text-align: left;">Logic + power switching</td>
<td style="text-align: left;">SMPS (5/12V), MCU, relays/triacs, IR receiver</td>
<td style="text-align: left;">$6–$18</td>
<td style="text-align: left;">$100–$300</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dual run capacitor (e.g., 35/5 µF)</td>
<td style="text-align: left;">Start/run motors</td>
<td style="text-align: left;">Metallized film; 3 terminals (C/HERM/FAN)</td>
<td style="text-align: left;">$2–$6</td>
<td style="text-align: left;">$15–$35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Filter-drier</td>
<td style="text-align: left;">Moisture/debris control</td>
<td style="text-align: left;">Molecular sieve; copper ODF</td>
<td style="text-align: left;">$1–$3</td>
<td style="text-align: left;">$6–$12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capillary tube + distributor</td>
<td style="text-align: left;">Fixed metering</td>
<td style="text-align: left;">Precision ID; cut-length; multi-port distributor</td>
<td style="text-align: left;">$1–$4</td>
<td style="text-align: left;">Bundled/low</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sheet metal &amp; plastics</td>
<td style="text-align: left;">Structure &amp; airflow</td>
<td style="text-align: left;">Stamping, powder-coat; injection molding</td>
<td style="text-align: left;">$20–$50</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">Harnesses, sensors, grommets, fasteners</td>
<td style="text-align: left;">Integration</td>
<td style="text-align: left;">NTC thermistors, connectors, rubber isolators</td>
<td style="text-align: left;">$8–$25</td>
<td style="text-align: left;">$15–$60</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Typical BOM subtotal (OEM, ex-works, high volume):</strong> $230–$360</p>
<p><em>Add labor, overhead, scrap, warranty reserve, packaging, logistics, margin → retail MSRP is 2–4× BOM.</em></p>
<p><em>Note:</em> Earlier rough totals (e.g., “$188” or compressor “$700–$2,600”) mixed scales/contexts. The table above reflects a realistic window-unit scope (not large commercial scrolls) with current commodity pricing.</p>
<section id="cost-estimation" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="cost-estimation"><span class="header-section-number">6.1</span> Cost Estimation</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Subsystem / Part Costs
</div>
</div>
<div class="callout-body-container callout-body">
<p>The following cost ranges are for common replacement parts in a ~1 ton (12k BTU) window/mini-split style system.</p>
</div>
</div>
<p><strong>Rotary compressor (~1 ton / 12k BTU, R‑410A)</strong><br>
- <strong>Function:</strong> Pumps refrigerant<br>
- <strong>Cost drivers:</strong> Capacity, refrigerant type, brand, current stock<br>
- <strong>Typical price:</strong> <strong>$231–$258</strong></p>
<p><strong>Evaporator coil (window unit)</strong><br>
- <strong>Function:</strong> Absorbs indoor heat<br>
- <strong>Cost drivers:</strong> Size, Cu/Al construction, OEM fitment<br>
- <strong>Typical price:</strong> <strong>$80–$180</strong></p>
<p><strong>Condenser coil (window unit)</strong><br>
- <strong>Function:</strong> Rejects heat outdoors<br>
- <strong>Cost drivers:</strong> Similar to evaporator coil<br>
- <strong>Typical price:</strong> <strong>$100–$170</strong></p>
<p><strong>Dual-shaft blower motor (115 V, small HP)</strong><br>
- <strong>Function:</strong> Drives indoor blower + outdoor prop fan<br>
- <strong>Cost drivers:</strong> Motor HP, speed taps, shaft configuration<br>
- <strong>Typical price:</strong> <strong>$180–$300</strong></p>
<p><strong>Indoor blower wheel (squirrel‑cage type)</strong><br>
- <strong>Function:</strong> Moves air across the evaporator<br>
- <strong>Cost drivers:</strong> Diameter, width, bore size<br>
- <strong>Typical price:</strong> <strong>$60–$170</strong></p>
<p><strong>Outdoor condenser fan blade (propeller type)</strong><br>
- <strong>Function:</strong> Moves air through the condenser coil<br>
- <strong>Cost drivers:</strong> Diameter, pitch, rotation side<br>
- <strong>Typical price:</strong> <strong>$43–$107</strong></p>
<p><strong>Control PCB / display (GE‑type)</strong><br>
- <strong>Function:</strong> Thermostat logic + power switching<br>
- <strong>Cost drivers:</strong> Model-specific design<br>
- <strong>Typical price:</strong> <strong>$100–$300</strong></p>
<p><strong>Run capacitor (dual, e.g.&nbsp;35/5 µF, 440V)</strong><br>
- <strong>Function:</strong> Starts and runs compressor + fan<br>
- <strong>Cost drivers:</strong> Mainly rating and brand (commodity part)<br>
- <strong>Typical price:</strong> <strong>$15–$35</strong></p>
<p><strong>Liquid-line filter-drier (¼” ODF)</strong><br>
- <strong>Function:</strong> Moisture/debris protection<br>
- <strong>Typical price:</strong> <strong>$6–$12</strong></p>
<p><strong>Capillary tube / distributor</strong><br>
- <strong>Function:</strong> Fixed-orifice metering<br>
- <strong>Typical price:</strong> <strong>(usually bundled with coils / low)</strong></p>
<p><strong>Miscellaneous (sensors, harness, louvers, filter, brackets)</strong><br>
- <strong>Function:</strong> Ancillary/OEM fit parts<br>
- <strong>Typical price:</strong> <strong>$15–$60</strong></p>
<hr>
</section>
<section id="typical-rehabilitation-bill-of-materials" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="typical-rehabilitation-bill-of-materials"><span class="header-section-number">6.2</span> Typical Rehabilitation Bill of Materials</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Categories group common <strong>repair bundles</strong> — what a tech would typically replace together.</p>
</div>
</div>
<p><strong>Minor refresh</strong><br>
- Includes: Capacitor, filter-drier, small sensors, cleanup<br>
- <strong>Parts cost range:</strong> <strong>$40–$120</strong></p>
<p><strong>Air-moving rehab</strong><br>
- Includes: Motor + blower wheel + condenser fan blade<br>
- <strong>Parts cost range:</strong> <strong>$280–$600</strong></p>
<p><strong>Sealed-system rehab</strong><br>
- Includes: Compressor + one coil (evap/cond) + filter-drier<br>
- <strong>Parts cost range:</strong> <strong>$350–$600+</strong><br>
- <strong>Note:</strong> This is <strong>before tools/labor</strong> for refrigerant work</p>
<p><strong>Electronics swap</strong><br>
- Includes: Control PCB + capacitor<br>
- <strong>Parts cost range:</strong> <strong>$120–$330</strong></p>
<hr>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hidden Costs:</strong><br>
Sealed-system jobs <strong>require refrigerant tools and EPA compliance</strong>, adding <strong>$200–$500+</strong> in overhead beyond part costs.</p>
</div>
</div>
</section>
<section id="fire-and-electrical-safety" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="fire-and-electrical-safety"><span class="header-section-number">6.3</span> Fire and Electrical Safety</h2>
<p>I’d advise to follow strict safety procedures. Never use a device with a damaged cord or plug, as this can lead to short circuits, fires, or electric shock. The device should be used with the correct fuse, and you should never overload power points by connecting too many appliances.</p>
<p>I advise to have A Class C fire extinguisher, which is designed for energized electrical fires, is the most effective choice. When not in use, it’s a good practice to unplug the device to prevent “phantom” power draw and to protect against power surges. If you notice any signs of a potential electrical issue, such as flickering lights, hot plugs, or a burning smell, cease use immediately and consult a qualified electrician.</p>
<p>WARNING: Capacitors can hold a dangerous electrical charge even after the unit is unplugged. They must be properly discharged before handling.</p>
<p>This is for education and research purpose only.</p>
</section>
<section id="regulatory-compliance" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="regulatory-compliance"><span class="header-section-number">6.4</span> Regulatory Compliance</h2>
<p>This is something, which I haven’t covered earlier. Almost all Air-conditioner units will go through compliance, before it enters into the market. In North-American market, it’s advisable to have EPA Section 608 certification, DOE SEER/EER efficiency compliance. In Indian market, you have BIS standards, BEE star-rating methodology. For both these, you’d have to submit application, report your unit, list your model. These are standard procedures that HVAC Systems need to follow.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusion</h1>
<p>Window-AC and Split ACs work to fulfil refrigeration cycle. In reality, We can appreciate how engineers worked on mastering the product and building for mass market. Both from Physicst and towards building one, it required lot of efforts, constant development. In engineering the product, certainly lot of trail and error.</p>
<p>In this post, we’ve dismantled a working unit, component by component, examined its inner workings, cost structures, assembly process. From the rotary compressor, hydrophilic evaporator coils to the dual-run capacitor, front-facing PCB logic boards, each element is designed with precision, efficiency.</p>
<p>We didn’t go deeper into how each of the components are manufactured, some of them certainly industrial masterpiece. Take Compressors, the manufacturing of them requires specialized equipment from metal stamping, forming, and welding for the main housing and rotor components, followed by precise assembly of the intricate mechanical parts like the meshing rotors, motor, and internal sealing elements.</p>
<p>This is to share how we are benefitted the fruits, labor of physicists, engineers, technicians and industrialists. The industrialists and investors have poured huge pool of capital in the process, that has allowed us to enjoy the benefits of Window-AC.</p>
<p>Finally, this teardown has given us the blueprint. We’ve mapped every component, understood its function, and decoded its cost. This is a blueprint, We’ve seen how they are assembled in a factory, Through two of our articles, we covered reasonable amount about Airconditioners. This understanding is enough to build, create a working prototype, which we will cover in the future.</p>
<div style="border-top: 2px solid #ccc; margin-top: 2em; padding-top: 1em; font-size: 0.95em; color: #555;">
<p>⚙️ Reverse-engineered and Written by <strong>Rick Rejeleene</strong></p>


</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ludwigwittgenstein2\.github\.io\/Tamil\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>