<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rick Rejeleene">
<meta name="dcterms.date" content="2026-06-28">
<meta name="description" content="A detailed ethnographic review of Nagarathar Chettiar Castes of Tamil Nadu">

<title>Nagarathar Chettiar: Social Group of Tamil Nadu – Notebook of Rick Rejeleene</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5d4d40b207192aa1b68a9430a7284735.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Notebook of Rick Rejeleene</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="http://rickrejeleene.me/"> <i class="bi bi-house-door-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://facebook.com/whitekangaroo"> <i class="bi bi-facebook" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/rick1776/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<!-- subscribe.html — simplified, no-JS Mailchimp form -->
<div id="mc_embed_signup">
  <form action="https://gmail.us12.list-manage.com/subscribe/post?u=1f588641ad0b06cbeecabd12b&amp;id=ca6e7ad445&amp;f_id=0028c0e1f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank">
    <h2>Subscribe</h2>
    <div class="mc-field-group">
      <label for="mce-EMAIL">Email Address</label>
      <input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="">
    </div>

    <!-- honeypot — DO NOT remove, Mailchimp needs it for bot protection -->
    <div style="position: absolute; left: -5000px;" aria-hidden="true">
      <input type="text" name="b_1f588641ad0b06cbeecabd12b_ca6e7ad445" tabindex="-1" value="">
    </div>

    <div>
      <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe">
    </div>
  </form>
</div>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul class="collapse">
  <li><a href="#historical-background" id="toc-historical-background" class="nav-link active" data-scroll-target="#historical-background">Historical Background</a></li>
  <li><a href="#caste-and-capitalism-in-colonial-india-by-david-west-rudner" id="toc-caste-and-capitalism-in-colonial-india-by-david-west-rudner" class="nav-link" data-scroll-target="#caste-and-capitalism-in-colonial-india-by-david-west-rudner">Caste and capitalism in colonial India by David West Rudner</a>
  <ul class="collapse">
  <li><a href="#concept" id="toc-concept" class="nav-link" data-scroll-target="#concept">Concept</a></li>
  <li><a href="#business" id="toc-business" class="nav-link" data-scroll-target="#business">Business</a></li>
  <li><a href="#ritual-and-kinship" id="toc-ritual-and-kinship" class="nav-link" data-scroll-target="#ritual-and-kinship">Ritual and Kinship</a></li>
  <li><a href="#chettiar-cuisine" id="toc-chettiar-cuisine" class="nav-link" data-scroll-target="#chettiar-cuisine">Chettiar Cuisine</a></li>
  <li><a href="#nagarathar-women" id="toc-nagarathar-women" class="nav-link" data-scroll-target="#nagarathar-women">Nagarathar Women</a></li>
  <li><a href="#offices-and-homes" id="toc-offices-and-homes" class="nav-link" data-scroll-target="#offices-and-homes">Offices and Homes</a></li>
  <li><a href="#career-path-and-job-training" id="toc-career-path-and-job-training" class="nav-link" data-scroll-target="#career-path-and-job-training">Career path and Job Training</a></li>
  <li><a href="#patriarch-of-nagarathar-chettiars" id="toc-patriarch-of-nagarathar-chettiars" class="nav-link" data-scroll-target="#patriarch-of-nagarathar-chettiars">Patriarch of Nagarathar Chettiars</a></li>
  </ul></li>
  <li><a href="#how-salt-traders-became-bankers" id="toc-how-salt-traders-became-bankers" class="nav-link" data-scroll-target="#how-salt-traders-became-bankers">How Salt Traders became Bankers?</a></li>
  <li><a href="#nagarathar-financial-system" id="toc-nagarathar-financial-system" class="nav-link" data-scroll-target="#nagarathar-financial-system">Nagarathar Financial System</a>
  <ul class="collapse">
  <li><a href="#deposits" id="toc-deposits" class="nav-link" data-scroll-target="#deposits">Deposits</a></li>
  <li><a href="#profit-and-interest-rates" id="toc-profit-and-interest-rates" class="nav-link" data-scroll-target="#profit-and-interest-rates">Profit and Interest Rates</a></li>
  <li><a href="#accounting" id="toc-accounting" class="nav-link" data-scroll-target="#accounting">Accounting</a></li>
  <li><a href="#the-adathi-parent-banker" id="toc-the-adathi-parent-banker" class="nav-link" data-scroll-target="#the-adathi-parent-banker">The Adathi: Parent Banker</a></li>
  <li><a href="#markets-where-chettiars-operated" id="toc-markets-where-chettiars-operated" class="nav-link" data-scroll-target="#markets-where-chettiars-operated">Markets where Chettiars Operated</a></li>
  <li><a href="#how-much-money-did-they-make" id="toc-how-much-money-did-they-make" class="nav-link" data-scroll-target="#how-much-money-did-they-make">How much money did they make?</a></li>
  <li><a href="#modern-banking" id="toc-modern-banking" class="nav-link" data-scroll-target="#modern-banking">Modern Banking</a></li>
  <li><a href="#phd-management-thesis-on-nagarathars" id="toc-phd-management-thesis-on-nagarathars" class="nav-link" data-scroll-target="#phd-management-thesis-on-nagarathars">PhD Management Thesis on Nagarathars</a></li>
  <li><a href="#insiders-perspectives" id="toc-insiders-perspectives" class="nav-link" data-scroll-target="#insiders-perspectives">Insider’s Perspectives</a></li>
  </ul></li>
  <li><a href="#decline-of-their-fortunes" id="toc-decline-of-their-fortunes" class="nav-link" data-scroll-target="#decline-of-their-fortunes">Decline of their Fortunes</a></li>
  <li><a href="#comparison-with-other-castes" id="toc-comparison-with-other-castes" class="nav-link" data-scroll-target="#comparison-with-other-castes">Comparison with other Castes</a></li>
  <li><a href="#a-chettiar-family-through-19th-and-20th-century" id="toc-a-chettiar-family-through-19th-and-20th-century" class="nav-link" data-scroll-target="#a-chettiar-family-through-19th-and-20th-century">A Chettiar Family through 19th and 20th Century</a>
  <ul class="collapse">
  <li><a href="#the-s.-rm.-m.-chettiar-family-banking-industry-education-and-politics" id="toc-the-s.-rm.-m.-chettiar-family-banking-industry-education-and-politics" class="nav-link" data-scroll-target="#the-s.-rm.-m.-chettiar-family-banking-industry-education-and-politics">The S. Rm. M. Chettiar Family: Banking, Industry, Education, and Politics</a></li>
  <li><a href="#generational-diagram" id="toc-generational-diagram" class="nav-link" data-scroll-target="#generational-diagram">Generational Diagram</a></li>
  </ul></li>
  <li><a href="#related-earlier-posts-on-caste" id="toc-related-earlier-posts-on-caste" class="nav-link" data-scroll-target="#related-earlier-posts-on-caste">Related Earlier Posts on Caste</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Nagarathar Chettiar: Social Group of Tamil Nadu</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Tamil Nadu</div>
    <div class="quarto-category">Caste</div>
    <div class="quarto-category">Anthropology</div>
    <div class="quarto-category">Sociology</div>
    <div class="quarto-category">Book Review</div>
    <div class="quarto-category">Entrepreneurship</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A detailed ethnographic review of Nagarathar Chettiar Castes of Tamil Nadu</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rick Rejeleene </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<nav id="TOC-body" role="doc-toc">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#historical-background" id="toc-historical-background">Historical Background</a></li>
  <li><a href="#caste-and-capitalism-in-colonial-india-by-david-west-rudner" id="toc-caste-and-capitalism-in-colonial-india-by-david-west-rudner">Caste and capitalism in colonial India by David West Rudner</a>
  <ul>
  <li><a href="#concept" id="toc-concept">Concept</a></li>
  <li><a href="#business" id="toc-business">Business</a></li>
  <li><a href="#ritual-and-kinship" id="toc-ritual-and-kinship">Ritual and Kinship</a></li>
  <li><a href="#chettiar-cuisine" id="toc-chettiar-cuisine">Chettiar Cuisine</a></li>
  <li><a href="#nagarathar-women" id="toc-nagarathar-women">Nagarathar Women</a></li>
  <li><a href="#offices-and-homes" id="toc-offices-and-homes">Offices and Homes</a></li>
  <li><a href="#career-path-and-job-training" id="toc-career-path-and-job-training">Career path and Job Training</a></li>
  <li><a href="#patriarch-of-nagarathar-chettiars" id="toc-patriarch-of-nagarathar-chettiars">Patriarch of Nagarathar Chettiars</a></li>
  </ul></li>
  <li><a href="#how-salt-traders-became-bankers" id="toc-how-salt-traders-became-bankers">How Salt Traders became Bankers?</a></li>
  <li><a href="#nagarathar-financial-system" id="toc-nagarathar-financial-system">Nagarathar Financial System</a>
  <ul>
  <li><a href="#deposits" id="toc-deposits">Deposits</a></li>
  <li><a href="#profit-and-interest-rates" id="toc-profit-and-interest-rates">Profit and Interest Rates</a></li>
  <li><a href="#accounting" id="toc-accounting">Accounting</a></li>
  <li><a href="#the-adathi-parent-banker" id="toc-the-adathi-parent-banker">The Adathi: Parent Banker</a></li>
  <li><a href="#markets-where-chettiars-operated" id="toc-markets-where-chettiars-operated">Markets where Chettiars Operated</a></li>
  <li><a href="#how-much-money-did-they-make" id="toc-how-much-money-did-they-make">How much money did they make?</a></li>
  <li><a href="#modern-banking" id="toc-modern-banking">Modern Banking</a></li>
  <li><a href="#phd-management-thesis-on-nagarathars" id="toc-phd-management-thesis-on-nagarathars">PhD Management Thesis on Nagarathars</a></li>
  <li><a href="#insiders-perspectives" id="toc-insiders-perspectives">Insider’s Perspectives</a></li>
  </ul></li>
  <li><a href="#decline-of-their-fortunes" id="toc-decline-of-their-fortunes">Decline of their Fortunes</a></li>
  <li><a href="#comparison-with-other-castes" id="toc-comparison-with-other-castes">Comparison with other Castes</a></li>
  <li><a href="#a-chettiar-family-through-19th-and-20th-century" id="toc-a-chettiar-family-through-19th-and-20th-century">A Chettiar Family through 19th and 20th Century</a>
  <ul>
  <li><a href="#the-s.-rm.-m.-chettiar-family-banking-industry-education-and-politics" id="toc-the-s.-rm.-m.-chettiar-family-banking-industry-education-and-politics">The S. Rm. M. Chettiar Family: Banking, Industry, Education, and Politics</a></li>
  <li><a href="#generational-diagram" id="toc-generational-diagram">Generational Diagram</a></li>
  </ul></li>
  <li><a href="#related-earlier-posts-on-caste" id="toc-related-earlier-posts-on-caste">Related Earlier Posts on Caste</a></li>
  <li><a href="#references" id="toc-references">References</a></li>
  </ul>
</nav>
<section id="historical-background" class="level1">
<h1>Historical Background</h1>
<p>As part of their community origin traditions, Nagarathar Chettiars believed that they came from Naganadu, which was destroyed by a flood or sea disaster centuries ago. Due to this, they are said to have migrated successively to Kanchipuram in Thondai Nadu, Kaveripoompattinam or Poompuhar in the Chola country, and finally to the Pandya country. These accounts should be understood as community traditions rather than securely established historical chronology<span class="citation" data-cites="thurston1909"><a href="#ref-thurston1909" role="doc-biblioref">[1]</a></span>.</p>
<p>They were a mercantile community rooted in the wider Chettinad region, including villages such as Kanadukathan and Athangudi near Karaikudi in Tamil Nadu. From at least the seventeenth century, the Chettiars were documented as salt traders, slowly transitioning into capital accumulation, distribution, lending, and investment, with offices in Ceylon, Burma, Singapore, and Malaya. Historically, they have been a predominantly Saivite mercantile community<span class="citation" data-cites="rudner1989"><a href="#ref-rudner1989" role="doc-biblioref">[2]</a></span>.</p>
<p>They were salt traders and an itinerant community of merchants who eventually established their homeland across parts of the present-day Sivaganga and Pudukkottai districts. Some community accounts trace their maritime trading history as far back as the eighth century. However, firm documentary evidence for their distinctive commercial activities begins mainly with their seventeenth-century salt trade<span class="citation" data-cites="rudner1989"><a href="#ref-rudner1989" role="doc-biblioref">[2]</a></span>.</p>
<p>Following the European and particularly British expansion in the Madras Presidency, they expanded their trading and moneylending enterprises. Occupationally, the Nagarathar moved from salt trading into cotton, rice, pearls, arrack, exchange banking, zamindari lending, and eventually Southeast Asian finance. Their greatest expansion came during the nineteenth century, when British colonial expansion and the opening of the Suez Canal connected Burma, Ceylon, and Malaya more closely to global markets for rice, plantation crops, rubber, and tin<span class="citation" data-cites="mahadevan1976"><a href="#ref-mahadevan1976" role="doc-biblioref">[3]</a></span>. In 1930, estimates of their aggregate capital and assets ranged from approximately Rs. 795 million to between Rs. 1.15 and Rs. 1.30 billion, depending on the source and the assets included.</p>
<p>The Nagarathar Chettiars organized much of their social life through nine predominantly Saivite clan temples, with Shiva and his consort as the principal deities. The canonical nine clan temples are Ilayathangudi, Iluppaikudi, Iraniyur, Mathur, Nemam, Pillaiyarpatti, Soorakudi, Vairavan, and Velangudi. Each married household, or pulli, was registered within the clan-temple system. Marriage, adoption, family recognition, conflict settlement, and community membership were mediated through these temples. The temples therefore served as important markers of community identity and belonging, while also administering endowments, maintaining records, and regulating marriage between the exogamous temple-clans.</p>
<p>Edgar Thurston<span class="citation" data-cites="thurston1909"><a href="#ref-thurston1909" role="doc-biblioref">[1]</a></span>, who co-authored the famous seven-volume Castes and Tribes of Southern India in 1909, recorded community traditions concerning their migration and settlement. A related tradition held that a Pandyan king encouraged the Nagarathars to settle in his kingdom because of their trading skills<span class="citation" data-cites="thurston1909"><a href="#ref-thurston1909" role="doc-biblioref">[1]</a></span>. This should be presented as a recorded origin tradition rather than as a verified historical event.</p>
<p>Colonial ethnographers and some community accounts described them as a high-status mercantile caste, sometimes aligning them with the Vaishya category, although South Indian caste realities were more complex than the four-varna model. Because of their tradition of religious giving, they donated extensively to the construction, renovation, and maintenance of numerous Saiva temples, choultries, schools, feeding houses, and other religious and charitable institutions, leaving an important legacy in the cultural heritage of Tamil Nadu and South India.</p>
</section>
<section id="caste-and-capitalism-in-colonial-india-by-david-west-rudner" class="level1">
<h1>Caste and capitalism in colonial India by David West Rudner</h1>
<figure style="text-align:center; margin:1.5rem auto; max-width:400px;" class="figure">
<img src="../../images/chettiar/bookcover.png" alt="Nagarathar Chettiar Book Cover" style="width:400px; height:auto; display:block; margin:0 auto;" class="figure-img">
<figcaption style="text-align:center; margin-top:0.5rem;">
Popular Scholarly Book on Nagarathar Chettiar
</figcaption>
</figure>
<p>The book is an examination of merchant-banking caste in Tamil Nadu. Merchant banking castes were vital to South Indian economy during 1700’s to 1950’s. The author, Anthropologist and scholar, David West Rudner, focuses on the Nagarathars of Tamil Nadu, also known as Chettiars. Chettiars are located in Chettinad area or specifically around Karaikudi, Chidambaram, Pudukottai town in Tamil Nadu.</p>
<p>The Book is laid out into three parts:</p>
<ul>
<li>Part 1) Concepts</li>
<li>Part 2) Business</li>
<li>Part 3) Ritual and Kinship</li>
</ul>
<section id="concept" class="level2">
<h2 class="anchored" data-anchor-id="concept">Concept</h2>
<p>Caste is characteristic unit of Indian Social Organization. Nagarathar caste were primarily mercantile bankers. As a community occupation, it is documented that they engaged with salt trading since 17th century. Unfortunately, Salt trading was disrupted by the 1792 drought and famine. It became less attractive after East India Company introduced special taxes for salt trading around 1805 in Madras Presidency. Occupationally, they played a middle role between Colonial British Government and local agrarian-communities in Tamil Nadu. Nagarathars monopolized market-share of money lending as their financial instrument. Mainly, they focused on family, business and God (saivism)</p>
<p>Surprisingly, they had less or few South Indian competitors in major markets. Through their business enterprises, acting as an extension of family kinship, they could scale and diversify into markets like Ceylon, Burma, Madras, Malaya. Nagarathars were primarily economic than political. Within the field of Anthropology, among South Indian Castes, Castes occupied a trade or specialized occupation. They played considerable role in financial, political role in early 20th century madras presidency.</p>
<p>David West Rudner, argues that Nagarathars are an argument against the famous Sociologist, Max Weber’s theory on incompatibility of Hinduism and Capitalism. Rudner’s major contribution is that he challenges the Weberian idea that Hindu caste society was incompatible with capitalism. The Nagarathars were not individualistic Western-style capitalists, but they were capitalist actors whose firms depended on caste trust, temple organization, kinship discipline, and reputation. Nagarathars functioned as communal capitalists. One could say, caste is symbolic capital. Symbolic capital is an anthropological concept. It captures how sociological relationships function for an individual in society. An individual has access to resources such as capital, human labor, kin groups based on honor, prestige, recognition. Through symbolical capital, an individual belonging to a caste could concretely mobilize as political factions to achieve a specific outcome. Castes do not have specific rights through symbolic capital. Castes are an enduring constellation of kinship, temple, territorial, reputational, and commercial institutions.</p>
</section>
<section id="business" class="level2">
<h2 class="anchored" data-anchor-id="business">Business</h2>
<p>This Chapter focuses on specific details on activities of Nagarathar business entities in Tamil Nadu, Ceylon, Burma, Malaya. Nagarathar’s business financial statement gives a detailed picture of their community. The chapter goes into specific details on balance sheet, income statement, affluence of Nagarathars. They extended their philanthropic activity in making religious gift to construct temples among their community. During 17th-19th century, India was the largest manufacturer of advanced goods, i.e.&nbsp;Textiles. Nagarathar’s built their commercial empire out of complex network of interdependent family business firms lending money to business. Along with their profit making intention, went hand in hand with moral good.</p>
</section>
<section id="ritual-and-kinship" class="level2">
<h2 class="anchored" data-anchor-id="ritual-and-kinship">Ritual and Kinship</h2>
<p>In Ritual and Kinship, David focuses on Dravidian kinship marriages. He goes in depth into various kinship and customs. For a non-Tamil or non-South Indian reader, this chapter might be fascinating due to unique rituals and kinships. Many of the kinship concepts do not extend as the same in Western world. Dravidian communities have customs in marriage with relatives, extended relatives, caste groups. Trust was essential ingredient. He says marriage was a negotiation between two descent groups.A Nagarathar boy was trained from young age in basic numeric, multiplication, accounting in the context of skills required for money lending and banking. Around teenage years, he would work as an apprentice in one of the family firms. Once he finished back, he was ready to get married, and take responsibility of leading the business step by step.</p>
<p>David West Rudner gives specific examples of famous Nagarathars. A notable one is Annamalai Chettiar, who founded Annamalai University in Chidambaram, Tamil Nadu. He was impressed by British Education. Politically in early 20th century, Justice Party in Tamil Nadu played an important role in Tamil patriotism. Nagarathars involved actively in Madras Presidency during this time. Raja Muttiah played important role in portraying Congress party, or party of Mahatma Gandhi as North Indian Brahmins. Northern Aggression or Hindi imposition would be upon Tamil people. Thus, Justice Party gained respect among Tamil people. They preferred British rule over Congress. Finally, Nagarathar’s influence extended to Indian Bank, Imperial Bank, Reserve Bank of India</p>
</section>
<section id="chettiar-cuisine" class="level2">
<h2 class="anchored" data-anchor-id="chettiar-cuisine">Chettiar Cuisine</h2>
<p>The historian S. Muthiah <span class="citation" data-cites="muthiah_chettiar_heritage"><a href="#ref-muthiah_chettiar_heritage" role="doc-biblioref">[4]</a></span> put the connection plainly, the Chettiars were traditionally vegetarians, and their lifecycle-ritual feasts remain vegetarian to this day, but trade carried them across peninsular India and Southeast Asia, where they absorbed non-vegetarian influences. From the late eighteenth century onward, after they established businesses in Ceylon, Burma, the Dutch East Indies, French Indo-China, and present-day Malaysia and Singapore, those influences became entrenched in Chettiar food habits.</p>
<p>The defining feature of Chettinad cooking is its reliance on freshly ground masalas and an unusually wide spice palette, star anise (anasipoo), the lichen kalpasi, tamarind, dried chillies, fennel, cinnamon, cloves, bay leaf, peppercorn, cumin, and fenugreek. That palette is a map of the trade routes traced in this essay. To the coconut, rice, and legumes of ordinary South Indian cooking, the Chettiars added Tellicherry pepper, Ceylon cardamom, Indonesian nutmeg, Madagascar cloves, galangal (blue ginger) from Laos and Vietnam. In Penang they acquired a taste for the sweet-sour register of Straits Chinese cooking, In Saigon they absorbed the herbs of Vietnamese food, and in Buddhist Ceylon they relaxed orthodox Hindu dietary prohibitions and came to eat meat.</p>
<figure style="text-align:center; display: inline-block;" class="figure">
<img src="../../images/chettiar/chettianduchicken.png" alt="Chettinad chicken" style="width:380px; height:350px; display:block; margin:0 auto;" class="figure-img">
<figcaption>
Chettinad chicken
</figcaption>
</figure>
<p>Chettinad chicken is reportedly the single most-ordered South Indian chicken preparation in restaurants across India. Chettinad food is bold, aromatic, and deeply flavorful. As it features a complex balance of fiery heat, earthy undertones, and a subtle tang. The food layers pungent whole spices with rich bases like coconut and tamarind to create a sophisticated, robust flavor profile.</p>
</section>
<section id="nagarathar-women" class="level2">
<h2 class="anchored" data-anchor-id="nagarathar-women">Nagarathar Women</h2>
<p>Nagarathar women were actively involved in financial services. They provided seed-capital, inherited their mother’s assets. Nagarathar-Marriage is mostly about matching economic status &amp; keeping their assets intact. One who spends extravagant amount of money for weddings receive highest honor, face. One, who invites 10-20,000 people for their son/daughter’s wedding gains prestige and highest honor. Nagarathars marry within the caste but outside their own temple clan, because the nine temple clans are exogamous. This allows them to retain social-financial kinship networks.</p>
<p>Nagarathar women are fed to believe, “Arranged Marriage” marrying same endogamy kin is honorable, face-giving<span class="citation" data-cites="Nishimura1998GenderKinshipPropertyRights"><a href="#ref-Nishimura1998GenderKinshipPropertyRights" role="doc-biblioref">[5]</a></span>. This is the majority belief among South-Indian Women/Castes. Accimar panam meant “married woman’s money.” At marriage, money from the bride’s family was placed in an interest-bearing account in her name. Additional gifts from parents, grandparents and maternal relatives could be added over time. Economically, it gave married women a degree of financial independence and security within the patriarchal structure of the community.</p>
<p>The money earned interest, provided security for the woman and her children, and helped finance her daughters’ future dowries. If she died without children, the money traditionally returned to her natal family. It therefore created a secondary channel through which wealth could pass from mothers and maternal relatives to daughters. However, although the money technically belonged to the woman, it was commonly invested in a Nagarathar firm and practically controlled by the groom’s valavu or joint family. Women possessed meaningful financial claims and family influence, but this did not amount to equal control over the predominantly male-managed banking system.<span class="citation" data-cites="rudner1994caste"><a href="#ref-rudner1994caste" role="doc-biblioref">[6]</a></span></p>
<p>The structure of the Chettiar business meant that for long stretches, the men simply were not there. Boys were trained from childhood, apprenticed in their teens, and then sent to firms in Rangoon, Colombo, Penang, or Singapore, often for years at a time. Someone had to hold the home together in Chettinad, and that someone was the wife.</p>
<p>We introduce the word, valavu, which carries two related meanings. Architecturally, the valavu is the ancestral house itself, built around the naduvasal or central courtyard, surrounded by the double rooms (rettaiarai), with an inner zone (irandamkattu) understood as the women’s domain. Socially, the valavu is the extended joint household: multiple pulli units, each a husband, wife, and children, living under a single patriarchal head, bound together for economic interdependence and business continuity. The two senses are really one idea. The great mansion was the joint family made physical, and when the men were abroad, the running of both, the building and the lineage inside it, fell substantially to the women who remained.</p>
</section>
<section id="offices-and-homes" class="level2">
<h2 class="anchored" data-anchor-id="offices-and-homes">Offices and Homes</h2>
<p>From 1830s-1960s, Tamil-Nagarathar’s were global financial lenders in East-Asia. As they operated collectively, they were raised for this specific career, they were in Singapore, Malaysia, Srilanka, Burma. A Typical Work-Bench for Nagarathar’s before computers came into existence. Mostly, Accountants and Financiers. They toiled, worked quite diligently, that funded the Mansions, Hindu Temples back in Tamil Nadu. Primarily, they wore simple clothes reflecting their modest lifestyle and work-ethic.</p>
<figure style="text-align:center; margin:1.5rem auto; max-width:400px;" class="figure">
<img src="../../images/chettiar/workdesk.png" alt="Workdesk of a Nagarathar" style="width:400px; height:auto; display:block; margin:0 auto;" class="figure-img">
<figcaption style="text-align:center; margin-top:0.5rem;">
Workdesk of a Nagarathar
</figcaption>
</figure>
<p>At their office, Chettiars lived spartan lifestyles, wearing simple white dhotis with sacred ash on their foreheads, sleeping on a mattress, disdaining extravagant luxuries. However they constructed opulent mansions in their villages, organizing lavish weddings with substantial dowry and ceremonial expenditure and coming of opulent age ceremonies. A Tamil Nagarathar’s Home, with close to 80 rooms. A Chettiar Mansion is spread over a sprawling 80,000 square feet area.</p>
<figure class="figure">
<img src="../../images/chettiar/mansion.png" alt="Chettiar Mansion" style="width:600px; height=700px; float:center;" class="figure-img">
<figcaption>
Mansion of a Nagarathar Chettiar
</figcaption>
</figure>
</section>
<section id="career-path-and-job-training" class="level2">
<h2 class="anchored" data-anchor-id="career-path-and-job-training">Career path and Job Training</h2>
<p>Long before Modern job descriptions, Tamil-Chettiars developed a structured apprenticeship system comparable to modern career ladders, carving career paths for their Men.</p>
<ol type="a">
<li>podiyan (office boy/Intern)</li>
<li>aduthaal (clerk)</li>
<li>kootali (agent)</li>
<li>pangaali (partner)</li>
<li>mudalaali (owner)</li>
</ol>
<figure style="width: 100%; max-width: 650px; margin: 1.5rem auto;" class="figure">
<img src="../../images/chettiar/careerladder.png" alt="Nagarathar Chettiar Career Ladder" style="width: 100%; height: auto; display: block;" class="figure-img">
<figcaption style="margin-top: 0.5rem; text-align: center;">
Career Ladder for Nagarathar Chettiar
</figcaption>
</figure>
<p>Chettiar business dealings centered around concepts like pattru (debit), varavu (credit), selavu (expenditure), laabam (profit) and nashtam (loss), recorded in documents called iynthogai, or trial balances, akin to modern income statement, balance statement.</p>
<p><strong>An Older Nagarathar Tamil Couple</strong></p>
<figure style="text-align:center; margin:1.5rem auto; max-width:400px;" class="figure">
<img src="../../images/chettiar/oldcouple.png" alt="An Older Nagarathar Tamil Couple" style="width:400px; height:auto; display:block; margin:0 auto;" class="figure-img">
<figcaption style="text-align:center; margin-top:0.5rem;">
An Older Nagarathar Tamil Couple
</figcaption>
</figure>
<p>The marriage necklace or the Chettiar thali was strung on a saradu or a black cord and comprised of palmette thalis ( 3, 5 or 7) interspersed with tubular or faceted long beads and with a central thali usually decorated with a Goddesses Lakshmi. Nagarathar women have three-times ceremonial weddings at different stages of life.</p>
</section>
<section id="patriarch-of-nagarathar-chettiars" class="level2">
<h2 class="anchored" data-anchor-id="patriarch-of-nagarathar-chettiars">Patriarch of Nagarathar Chettiars</h2>
<p>Sathappa Ramanatha Muthiah Chettiar (1840-1900), the merchant, leader of the Nagarathar community of Chettinad community. Sathappa was not educated, he worked tirelessly to build Hindu Temples.</p>
<figure style="text-align:center; margin:1.5rem auto; max-width:400px;" class="figure">
<img src="../../images/chettiar/Santhanpan.png" alt="Sathappa Ramanatha Muthiah Chettiar" style="width:400px; height:auto; display:block; margin:0 auto;" class="figure-img">
<figcaption style="text-align:center; margin-top:0.5rem;">
Chettiar-Patriarch of the influential S. Rm. M. family &amp; the Chettiar community
</figcaption>
</figure>
<p>Nagarathar Family, in early 20th century. Ilayathangudi Kovil (Temple) located near Karaikudi, Tamil Nadu. India. The Russians have Dacha (дача), a Guest-House or Second-Home, Americans say, Vacation Home. Nagarathar’s built choultries, guest-house for travellers, mostly close to Hindu Temples.</p>
</section>
</section>
<section id="how-salt-traders-became-bankers" class="level1">
<h1>How Salt Traders became Bankers?</h1>
<p>As Salt Trading was their primary business, I wondered how did they become Bankers? They were early salt trader, who had expanded all over South India. Salt Trading allowed them to accumulate capital, connect with wider part of wholesale commerce, transport, and merchant networks. They were still salt merchants in the early 18th century, and Salt Trading was slowly becoming unprofitable. They gradually shifted their focus to banking and financial services, leveraging their accumulated capital and extensive networks to establish a strong presence in the financial sector.</p>
<p><strong>Hundi</strong></p>
<p>Already a system of Hundi, which was an indigenous system of exchange used by Chettiars, before SWIFT or Western Union existed. A Hundi was an IOU written order, that could travel. A merchant in Rangoon needing capital could receive it against a hundi drawn on a Chettiar firm in Madras, redeemable across an entire network of family firms. Hundreds of independent Chettiar family firms worked using this system, had their own internal accounting that would be familiar to auditors now.</p>
<p>The hundi system was powerful because it converted trust into mobility. A merchant in Rangoon could draw a hundi through a Chettiar firm and have it honored in another town where another Chettiar firm operated. The client did not need to carry bags of silver or cash. He carried a written instrument backed by the reputation of the Chettiar network.</p>
<div class="family-table">
<div id="tbl-hundi-types" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[28,20,52]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hundi-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Types of hundi and their functions
</figcaption>
<div aria-describedby="tbl-hundi-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 20%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hundi type</th>
<th style="text-align: left;">Meaning</th>
<th style="text-align: left;">Function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Darisanai hundi</strong> / <strong>Dharshan hundi</strong></td>
<td style="text-align: left;">Sight hundi</td>
<td style="text-align: left;">Payable on sight, like a demand draft</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Nadappu hundi</strong></td>
<td style="text-align: left;">Current hundi</td>
<td style="text-align: left;">No fixed term; paid according to convenience, with interest calculated until encashment</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Thavanai hundi</strong></td>
<td style="text-align: left;">Fixed-term hundi</td>
<td style="text-align: left;">Payable after a specified term; could be discounted</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Pay-order hundi</strong></td>
<td style="text-align: left;">Dowry-related instrument</td>
<td style="text-align: left;">Used in relation to dowry or <em>stridhan</em> payments</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p>This worked because Chettiar firms trusted each other. A hundi could pass through two or three bankers before final settlement. In many cases, the first banker collected the discount or commission, while intermediate bankers did not repeatedly charge the client. This made Chettiar hundis attractive for merchants, migrants, and traders who needed to remit funds across long distances</p>
</section>
<section id="nagarathar-financial-system" class="level1">
<h1>Nagarathar Financial System</h1>
<p>Each family firm functioned like a small bank, but all these firms together formed a larger caste-based financial system. Their capital moved through kinship, marriage, caste trust, temple funds, deposits, bills of exchange, and overseas branch offices. They used their own jargon and practices, which were distinct from the Western banking systems of the time.</p>
<p>The office or business house was often called a kittangi. The kittangi was simple in its structure, often consisting of a small office or shop where the family’s financial transactions were managed. It was a compact financial workspace: ledgers, cash boxes, correspondence, account books, clerks, apprentices, agents, and visiting clients. From such offices, the Nagarathars financed agriculture, rice trade, plantations, retail trade, money transfer, mortgage lending, and commercial credit across Burma, Ceylon, Malaya, Singapore, and South India.</p>
<p>The Nagarathar’s pooled many resources and worked together for their funds.</p>
<div class="family-table">
<div id="tbl-capital-sources" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[26,24,50]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-capital-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Sources of Nagarathar banking capital and their functions
</figcaption>
<div aria-describedby="tbl-capital-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Meaning</th>
<th style="text-align: left;">Function in the financial system</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>mudal panam</strong></td>
<td style="text-align: left;">Proprietor’s own capital</td>
<td style="text-align: left;">The owner’s original capital invested in the firm</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>mempanam</strong></td>
<td style="text-align: left;">Surplus or outside funds</td>
<td style="text-align: left;">General term for funds beyond the proprietor’s own money</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>aachimar panam</strong> / <strong>accimar panam</strong></td>
<td style="text-align: left;">Women’s or dowry deposits</td>
<td style="text-align: left;">Money belonging to wives, daughters-in-law, or female kin, often deposited into the firm</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>thanadumurai panam</strong> / <strong>thandu morai panam</strong></td>
<td style="text-align: left;">Deposits from relatives and fellow Nagarathars</td>
<td style="text-align: left;">Capital from kin, lineage, clan, village, and caste networks</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>kovil panam</strong> / <strong>dharma panam</strong></td>
<td style="text-align: left;">Temple money</td>
<td style="text-align: left;">Temple funds deposited into business rather than kept idle</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>adathi kadai panam</strong></td>
<td style="text-align: left;">Money from parent bankers</td>
<td style="text-align: left;">Funds advanced by larger parent-bankers to smaller or dependent firms</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>vellaikkaran panam</strong></td>
<td style="text-align: left;">European bank money</td>
<td style="text-align: left;">Short-term loans from European banks to selected elite Chettiar bankers</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p>Funds were pooled as many resources as possible. A successful proprietor could take deposits from relatives, women’s dowry funds, temples, fellow Chettiars, larger parent-bankers, clients, and sometimes European banks. He then lent this money at a higher rate to cultivators, traders, landlords, estate owners, or other borrowers. Profit came from the spread between borrowing cost and lending return.</p>
<p>Caste was a credit network, A Chettiar banker could trust another Chettiar because the relationship was embedded in family, marriage, temple, village, and reputation. If a man failed dishonorably, he did not merely lose one transaction. He risked losing marriage alliances, caste standing, access to deposits, and future business opportunities.</p>
<section id="deposits" class="level2">
<h2 class="anchored" data-anchor-id="deposits">Deposits</h2>
<p>The Nagarathars used different kinds of deposit accounts. These were not identical to modern bank accounts, but they performed similar functions.</p>
<p>The kadai kanakku, literally “shop account,” was a current account maintained in the business house. It included demand deposits and nadappu deposits. The word nadappu means “current” or “walking.” A nadappu deposit was not a fixed deposit in the modern sense. It was a moving account between Chettiar bankers, and the nadappu vatti or current interest rate became a benchmark rate for the community.</p>
<p>The thavanai kanakku was a fixed-term account. Thavanai means installment, term, or fixed period. These were usually two-month, three-month, or six-month deposits. They were important because they gave the firm predictable working capital. A banker could plan loans because he knew that the depositor would not suddenly withdraw the money.</p>
<p>The vayan vatti kanakku was a fixed-interest account, often associated with non-Chettiar depositors. These accounts paid interest, but they did not carry the same caste-based flexibility as deposits between Nagarathars.</p>
<p>The money did not sit idle, Even dowry money, temple money, or surplus family money could be deposited into a firm and made productive. This was the Nagarathar idea of perukkuradhu, multiplying money. Capital was not to be consumed. It was to be circulated, lent, reinvested, and multiplied. Ideally, a family should live from interest or profit, not by eating into the principal.</p>
</section>
<section id="profit-and-interest-rates" class="level2">
<h2 class="anchored" data-anchor-id="profit-and-interest-rates">Profit and Interest Rates</h2>
<p>The Chettiars made money primarily through interest margins. They borrowed or accepted deposits at one rate and lent at a higher rate.</p>
<div class="family-table">
<div id="tbl-return-by-region" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[40,60]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-return-by-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Approximate return on capital by region <span class="citation" data-cites="rudner1994caste"><a href="#ref-rudner1994caste" role="doc-biblioref">[6]</a></span>
</figcaption>
<div aria-describedby="tbl-return-by-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: right;">Approximate return on capital</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">India</td>
<td style="text-align: right;">8–9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ceylon</td>
<td style="text-align: right;">10–12%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Burma</td>
<td style="text-align: right;">12–15%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malaya</td>
<td style="text-align: right;">15–18%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p>Their overseas business was more profitable than their South Indian business, but also riskier. Burma, Malaya, and Ceylon offered higher returns because agriculture, plantations, land markets, and trade needed credit. These regions, exposed the Chettiars to depression, political resentment, land legislation, war, and nationalization.</p>
<p>In Malaya, some rural loans could carry much higher rates, especially when secured against land and given in risky conditions. In some cases, interest rates could reach 24% or even 36% per year. This is why colonial officials, local farmers, and later nationalist critics often accused Chettiar lenders of usury. But from the Chettiar side, they saw themselves as taking high risk, lending quickly, and providing capital where formal banks would not lend.</p>
<p>Their Business Model: 1. Collect capital from family, women’s funds, temples, fellow Chettiars, clients, and European banks. 2. Pay depositors an agreed interest rate. 3. Lend the money to borrowers at a higher rate. 4. Use land, crops, jewels, promissory notes, mortgages, and reputation as security. 5. Reinvest part of the profit instead of consuming the principal. 6. Use caste trust to keep the network liquid and reliable.</p>
<figure class="figure">
<img src="../../images/chettiar/riskreward.png" alt="Risk and Reward" style="width:800px; height=800px; float:center;" class="figure-img">
<figcaption>
Risk and Reward
</figcaption>
</figure>
</section>
<section id="accounting" class="level2">
<h2 class="anchored" data-anchor-id="accounting">Accounting</h2>
<p>The Nagarathars were extremely careful accountants. While they did not have Western double-entry bookkeeping. They were disciplined, detailed, and commercially effective.</p>
<div class="family-table">
<div id="tbl-accounting-terms" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[28,72]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-accounting-terms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Nagarathar accounting terminology and ledgers
</figcaption>
<div aria-describedby="tbl-accounting-terms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 72%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>pattru</strong></td>
<td style="text-align: left;">Debit</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>varavu</strong></td>
<td style="text-align: left;">Credit</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>selavu</strong></td>
<td style="text-align: left;">Expenditure</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>laabam</strong></td>
<td style="text-align: left;">Profit</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>nashtam</strong></td>
<td style="text-align: left;">Loss</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>vatti</strong></td>
<td style="text-align: left;">Interest</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>peredu</strong></td>
<td style="text-align: left;">Major ledger recording client relationships and transactions</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>pekki pustakam</strong></td>
<td style="text-align: left;">Book of outstanding dues, debts, and deposits</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>vatti chitti</strong></td>
<td style="text-align: left;">Interest calculation sheet</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>kurippu</strong></td>
<td style="text-align: left;">Daily cash book</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>ainthogai</strong> / <strong>iynthogai</strong></td>
<td style="text-align: left;">Balance-sheet-like summary, often described as containing capital, borrowings, investments, outstandings, and profits</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p>Their ledgers were client-centered. The purpose was to know exactly who owed what, what deposits were held, what interest was due, what payments had been made, and what relationship the firm had with each borrower or depositor. The account books acted almost like a social map of credit. They did not merely record money; they recorded trust, obligation, family capital, temple capital, and commercial reputation. A Chettiar boy was trained into this world from childhood. He learned arithmetic, multiplication, interest calculation, ledger discipline, and business vocabulary. He might begin as a podiyan or office boy, then become aduthaal or clerk, then kootali or agent, then pangaali or partner, and finally mudalaali or proprietor. This was a structured career ladder before modern corporate job descriptions</p>
</section>
<section id="the-adathi-parent-banker" class="level2">
<h2 class="anchored" data-anchor-id="the-adathi-parent-banker">The Adathi: Parent Banker</h2>
<p>The word is often translated as “parent banker.” An adathi was a large, trusted, elite banker who could provide funds to smaller firms, vouch for them, and maintain relationships with European banks.</p>
<p>Only the largest and most reputable firms could borrow from European banks.</p>
<ol type="1">
<li>European banks lent to the biggest Chettiar firms.</li>
<li>Big Chettiar adathis lent to smaller Chettiar firms.</li>
<li>Smaller Chettiar agencies lent to cultivators, traders, landlords, merchants, and plantation interests.</li>
<li>Deposits flowed upward and sideways through kinship, caste, temple, and client networks.</li>
<li>Hundis allowed money and credit to move across distance.</li>
</ol>
</section>
<section id="markets-where-chettiars-operated" class="level2">
<h2 class="anchored" data-anchor-id="markets-where-chettiars-operated">Markets where Chettiars Operated</h2>
<p><strong>Burma</strong></p>
<p>Burma was the largest and most important field of Chettiar expansion. The growth of rice cultivation in Lower Burma required credit. Farmers needed money for cultivation, land tax, seed, cattle, labor, and household expenses. Formal European banks usually did not lend directly to small cultivators. Chettiars filled this gap.</p>
<p>By 1930, estimates suggest that Chettiar capital in Burma may have been around ₹75 crore. Other estimates mention about ₹50 crore worth of lending, and annual Chettiar loans in Burma of about ₹10–12 crore. These were staggering sums for the period. By one account, Chettiar loans formed about 70% of the total loans lent in Burma.</p>
<p>The firm network was dense. Around 1910, there were about 350 Chettiar firms in Burma. By 1930, this had grown to about 1,650 representative offices. Rangoon alone had hundreds of Chettiar offices. Moghul Street in Rangoon was especially associated with Chettiar moneylenders, with many shops operating from clustered kittangis.</p>
<p>Most loans in Burma were agricultural. A farmer borrowed before cultivation and repaid after harvest. The security was often land. This worked during good years, but the Great Depression damaged the system. Rice prices fell, farmers could not repay, and land began to pass into Chettiar hands through mortgage foreclosure or debt settlement. Many Chettiars became absentee landlords, not necessarily because they wanted to farm, but because unpaid debt converted into land ownership.</p>
<p>Burmese resentment grew. Anti-Indian and anti-Chettiar sentiment intensified. Later, political change, Japanese invasion, separation of Burma from India, land reforms, and nationalization caused enormous losses to Chettiar firms.</p>
<p><strong>Ceylon, Malaya, Singapore</strong></p>
<p>Ceylon was another important field. Chettiars financed plantations, estates, retail shops, rice trade, mortgages, pawnbroking, and other advances. One 1934 estimate placed Nagarathar assets in Ceylon at about ₹10 crore. These assets included agricultural land and estates, residential property, business capital, pawnbroking advances, mortgage loans, other advances, and deposits in British banks.</p>
<p>In Malaya, Chettiar finance was tied to land, rice cultivation, rubber, tin, and migrant trade. Loans were often secured by land mortgages. In some cases, farmers could borrow quickly from Chettiars even when banks or government credit systems were slow or unavailable. This speed made the Chettiars useful; the high interest made them controversial.</p>
<p>In Singapore and the Straits Settlements, Chettiars were important in remittance, trade finance, and banking. In Cochin China and Saigon, they also operated moneylending networks, though political upheaval and anti-moneylender policies later weakened them.</p>
<figure class="figure">
<img src="../../images/chettiar/workingcapital.png" alt="Overseas Working Capital" style="width:800px; height=800px; float:center;" class="figure-img">
<figcaption>
Overseas Working Capital
</figcaption>
</figure>
</section>
<section id="how-much-money-did-they-make" class="level2">
<h2 class="anchored" data-anchor-id="how-much-money-did-they-make">How much money did they make?</h2>
<p>The historical sources usually tell us more about capital controlled, assets, loans, and working capital than about exact net profit.</p>
<div class="family-table">
<div id="tbl-working-capital" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[68,32]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-working-capital-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Estimates of Nagarathar working capital and assets, c.&nbsp;1930 <span class="citation" data-cites="rudner1994caste"><a href="#ref-rudner1994caste" role="doc-biblioref">[6]</a></span>
</figcaption>
<div aria-describedby="tbl-working-capital-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 68%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estimate / location</th>
<th style="text-align: right;">Approximate amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total Nagarathar working capital, 1930 — low estimate</td>
<td style="text-align: right;">₹79.5 crore</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total Nagarathar working capital, 1930 — high estimate</td>
<td style="text-align: right;">₹115–130 crore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Burma working capital, 1930 estimate</td>
<td style="text-align: right;">₹75 crore</td>
</tr>
<tr class="even">
<td style="text-align: left;">Federated Malay States working capital estimate</td>
<td style="text-align: right;">₹25 crore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ceylon working capital estimate</td>
<td style="text-align: right;">₹14 crore</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cochin China working capital estimate</td>
<td style="text-align: right;">₹5 crore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Madras Presidency working capital estimate</td>
<td style="text-align: right;">₹1 crore</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ceylon assets, 1934 estimate</td>
<td style="text-align: right;">about ₹10 crore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Annual Chettiar loans in Burma, around 1930</td>
<td style="text-align: right;">about ₹10–12 crore</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indian Bank deposits, around 1930</td>
<td style="text-align: right;">about ₹1.92 crore</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p>A small caste community from Chettinad had built a financial system whose working capital ran into tens of crores in the 1930s. In Burma alone, their capital was comparable to large colonial investments. But the wealth was not equally distributed among all Nagarathars. A handful of elite families and large firms controlled enormous funds; many medium firms depended on parent bankers; smaller firms operated as agents or sub-agents within the wider network.</p>
<p>By 1930, their working capital likely ranged from about ₹79.5 crore to ₹120–130 crore. Burma alone may have accounted for about ₹75 crore. These figures make the Nagarathars one of the most important indigenous financial communities in colonial South and Southeast Asia.</p>
</section>
<section id="modern-banking" class="level2">
<h2 class="anchored" data-anchor-id="modern-banking">Modern Banking</h2>
<p>The Nagarathars also moved into modern banking. Arbuthnot &amp; Co was a prominent British bank firm established in Madras around 1807. It was started by George Arbuthnot a Scot who arrived in Madras in 1800. One of the partners in 1900s, engaged in speculation, and in the process, lost huge amounts of the firm’s money. Arbuthnots employed between 11,000 and 12,000 people, had 7,000 creditors and £1,000,000 in liabilities.</p>
<p>The collapse of Arbuthnot &amp; Co.&nbsp;in Madras created a crisis of trust in European banking. Indian Bank was founded in 1907, and although the initial promoters were not all Chettiars, Chettiar capital became crucial to its growth. Within one year, its paid-up capital rose from ₹10 lakh to ₹17.75 lakh, with a large portion subscribed by Chettiars. By 1930, its deposits were about ₹1.92 crore<span class="citation" data-cites="rudner1994caste"><a href="#ref-rudner1994caste" role="doc-biblioref">[6]</a></span>.</p>
<p>Later, Chettiar families were associated with Indian Overseas Bank, Bank of Madura, insurance companies, textile mills, educational institutions, and industrial ventures. This shows that the community did not remain only in traditional moneylending. After colonial-era disruptions, some elite families transitioned into formal banking, industry, education, insurance, and philanthropy.</p>
<p>In C.J. Kuncheria’s Case of Chettiar, an Unpublished Essay, He says, As the 20th century emerged, Burma emerged as the world’s biggest exporter of rice and one of the richest provinces of the empire and by 1929, there were 1,650 Chettiar agencies in Burma, with an estimated 750 million rupees of working capital in play. This compared with 700 agencies in the Federated Malay States and the Straits Settlements, 450 in Ceylon and 105 in Indo-China. Working capital in these territories stood at 250 million rupees in the Federated Malay States and the Straits Settlements, 140 million rupees in Ceylon, 50 million rupees in Indo-China, and 10 million in Madras”<span class="citation" data-cites="kuncheria_chettiars"><a href="#ref-kuncheria_chettiars" role="doc-biblioref">[7]</a></span></p>
</section>
<section id="phd-management-thesis-on-nagarathars" class="level2">
<h2 class="anchored" data-anchor-id="phd-management-thesis-on-nagarathars">PhD Management Thesis on Nagarathars</h2>
<p>In this, a PhD management thesis on Nagarathars are discussed extensively. The author applies, qualitative longitudinal case study methodology in her study, using primary and secondary data: interviews, open-ended questionnaires, field visits to Chettinad towns and villages, field visit to Singapore, observation of marriages and social gatherings, old books, archives, journals, letters, diaries, British India publications.</p>
<p>In this, the author explains business practices, geographical spread, social structure of Nagarathars, and historical transition of occupations.</p>
<p><a href="files/NattukottaiPhD.pdf">Open the PDF</a></p>
<iframe src="files/NattukottaiPhD.pdf" width="100%" height="850px" style="border: 1px solid #ddd; border-radius: 8px;">
</iframe>
</section>
<section id="insiders-perspectives" class="level2">
<h2 class="anchored" data-anchor-id="insiders-perspectives">Insider’s Perspectives</h2>
<p>The following is excerpted from the PhD thesis. Punitha discusses insider criticisms from elderly Chettiar women in the section “Insider’s Perspectives,” including memories of losses after Burma and criticisms of interest-accounting practices <span class="citation" data-cites="punitha2016"><a href="#ref-punitha2016" role="doc-biblioref">[8]</a></span>.</p>
<p>Another interesting viewpoint is that “chettiars does not regard usury as a sin”. Contradictory to that, in an interview session, the researcher came through two interesting criticisms. One is from the female member of the community, an “aachi” aged 65.</p>
<p>The content she shared is as follows: “My father worked in Burma and came to India during Japan bombings during the world war II walking all the way from Burma to India. We were such a wealthy family. We lost everything after that, as there was no other occupation found suitable. All the wealth drained in rearing the big family. Our elders think that it is the curse of the poor farmers of Burma who lost their lands and felt cheated by chettiars”</p>
<p>The other old aachi, aged 72, said “ aadikku thai pathu maasamnu kannakku ezhudhi setha sothu” meaning the tamil months “aadi” and “thai” comes in sequence of seven months, but written in the account books as 10 months, and interest charged for more period than necessary.</p>
<p>Many of the Chettiars and Chettiar women, wanted to suppress the negative side of the communities’ business practices, not wanting to be the one who tarnished the glorifying image of the community in the outside world. They want to keep all their short comings among themselves, by crucifying, commenting, judging, finding fault and cursing their own actions without any hesitation among themselves.</p>
<p>This characteristic was often observed by the researcher. When confronted with questions about the community in open, they talk only about the glory and nothing else. Hence, it can be considered either they didn’t realize usury is a sin or it is not an act of usury at all as depicted by others.</p>
<p>To summarise, it is understood from the above analysis that chettiars were very strict in their occupation and there was no charity in the money lending operations. They were not willing to leave a single penny which is rightfully theirs. On the other hand, they were ready to donate without a second thought huge amounts of money for temple renovations, building new temples or educational institutions. Hence, we can generalize that they had a value line drawn between their profession and personal feelings. They were kind and altruistic but displayed opposite behavior in profession.</p>
</section>
</section>
<section id="decline-of-their-fortunes" class="level1">
<h1>Decline of their Fortunes</h1>
<p>The Nagarathars were among the most skilled indigenous bankers of South and Southeast Asia. Infact, in Madras Presidency, they were the most successful financial social group<span class="citation" data-cites="rudner1994caste"><a href="#ref-rudner1994caste" role="doc-biblioref">[6]</a></span> in the last few centuries<span class="citation" data-cites="punitha2016"><a href="#ref-punitha2016" role="doc-biblioref">[8]</a></span>.</p>
<p>Their wealth was built in a specific colonial economy, as they moved capital from Chettinad into Burma, Ceylon, Malaya, Singapore, and Saigon. They lent money to cultivators, traders, landholders, and merchants. They worked through kittangis, agency houses, hundis, deposits, loans, and kinship-based trust networks.<span class="citation" data-cites="punitha2016"><a href="#ref-punitha2016" role="doc-biblioref">[8]</a></span> This system worked when money<span class="citation" data-cites="jain1929"><a href="#ref-jain1929" role="doc-biblioref">[9]</a></span>, land, people, and legal contracts<span class="citation" data-cites="rudner1994caste"><a href="#ref-rudner1994caste" role="doc-biblioref">[6]</a></span> could move across the British imperial world.</p>
<p>It had its vulnerability, The greatest blow came from Burma, Chettiar capital was deeply tied to Burmese agriculture, especially rice cultivation. When borrowers defaulted, land often passed into Chettiar hands, leading to a significant loss of capital. This made them, Politically hated. The Burmese peasants saw them as outsiders who had taken land. Anti-Indian and anti-moneylender feeling grew. Then came the Great Depression, rice-price collapse, Japanese invasion during World War II, emergency flight from Burma, and finally Burmese nationalism and land nationalization. Many Chettiars had to leave behind land, houses, account books, debts, and business networks.</p>
<p>In Ceylon, the situation was similar, brought another kind of decline. There, Chettiars were important merchant-bankers and intermediaries between European banks and local borrowers.<span class="citation" data-cites="weerasooria1973"><a href="#ref-weerasooria1973" role="doc-biblioref">[10]</a></span> But the Chetty crisis of the 1920s damaged<span class="citation" data-cites="subramaniam2016"><a href="#ref-subramaniam2016" role="doc-biblioref">[11]</a></span> confidence in their firms. Laws regulating moneylending, business names, pawnbroking, taxation, citizenship, and foreign ownership gradually restricted their operations. After Ceylon’s independence, many Chettiars were treated as non-citizens or temporary residents. The Finance Act of 1961 became especially damaging because it restricted non-Ceylonese from moneylending.</p>
<p>Some Chettiar families converted liquid capital into palatial houses, status competition, expensive marriages, religious donations, and non-productive displays of wealth. The mansions of Chettinad are beautiful, but for many middle-level firms they became illiquid assets. They showed wealth, but they did not multiply capital. When overseas income stopped, these houses became expensive to maintain. Families that once had cash flow<span class="citation" data-cites="unesco2014"><a href="#ref-unesco2014" role="doc-biblioref">[12]</a></span> from Burma or Ceylon now had large households, social obligations, and inherited prestige without the same income.<span class="citation" data-cites="punitha2016"><a href="#ref-punitha2016" role="doc-biblioref">[8]</a></span></p>
<p>However, some survived the economic downturns and continued to transition. A few elite families moved successfully into textiles, banking, plantations, cinema, industry, education, and philanthropy. But many middle and smaller Chettiar firms could not make the transition from indigenous merchant<span class="citation" data-cites="ito1966"><a href="#ref-ito1966" role="doc-biblioref">[13]</a></span> banking to modern corporate capitalism.<span class="citation" data-cites="punitha2016"><a href="#ref-punitha2016" role="doc-biblioref">[8]</a></span></p>
</section>
<section id="comparison-with-other-castes" class="level1">
<h1>Comparison with other Castes</h1>
<p>In my earlier writing <span class="citation" data-cites="rejeleene2025tamillibrary"><a href="#ref-rejeleene2025tamillibrary" role="doc-biblioref">[14]</a></span>, I had noticed that the Nagarathar’s had limitation. Due to being traditional, marrying only within their own community, they were limited in their social and economic conditions. While, Marwaris also married within their own community, they also practiced social conservativism, women were expected to stay at home, and were discouraged from gaining an education. Between reformers and traditionalists, there was a constant tension on the independence of women.</p>
<p>The Marwaris made the jump the Chettiars mostly did not, out of indigenous moneylending and into modern industry. G. D. Birla, desperate to move from trader to industrialist, set up his first jute mill in Calcutta despite British and Scottish merchants trying to choke off his bank credit and machinery imports. Ramkrishna Dalmia moved into cement, sugar, paper, and pipes; Jamnalal Bajaj came up through sugar trading and rose to prominence.</p>
<p>After the Second World War the community turned decisively to industry, and by 1970 the Marwaris controlled much of the nation’s private industrial assets; by 2011 they accounted for roughly a quarter of the Indians on the Forbes billionaire list. One might ask, Why did the Nagarathars not follow a similar path? Nagarathars capital was concentrated overseas, in Burma, Ceylon, and Malaya, colonial economies that were nationalized, invaded, or legislated against, so that the Chettiar fortune was largely destroyed by forces outside India. And as a result, their capital faced geography of risk and lost their fortunes.</p>
<p>One major limitation is that, they were the closest to building modern South Indian financial capital markets that would have transformed further the region. If they had expanded, socialized with other communities, including people from the West, and were aware of modern financial practices, they might have been able to overcome these limitations.</p>
<p>The Western financial system went further than either community by building institutions that outlived any single family, investment banks, stock exchanges, securities-underwriting houses, and large financial conglomerates. Financial Institutions and instruments in the West, included investment banks, stock exchanges, securities underwriting houses, or large financial conglomerates. However, Nagarathar’s large amount of capital moved into education, temples, philanthropy, real estate, industry, politics, and trusts, rather than financial innovation.</p>
<p>The Industrial Banking of the West looked like the following:</p>
<ol type="1">
<li>Raise money from investors</li>
<li>Underwrite securities</li>
<li>Reorganize companies</li>
<li>Merge firms</li>
<li>Place directors</li>
<li>Stabilize industries</li>
<li>Create national corporations.</li>
</ol>
<p>This is how Western investment banking became powerful. J.P. Morgan was central to railroad finance, industrial consolidation, and the creation of U.S. Steel.</p>
</section>
<section id="a-chettiar-family-through-19th-and-20th-century" class="level1 page-columns page-full">
<h1>A Chettiar Family through 19th and 20th Century</h1>
<p>There are many chettiar families in Tamil Nadu, each with its own unique history and contributions to the region’s development. In this, We choose example from many families, primarily to notice their occupation, generational wealth, and the transformation of the family across different centuries.</p>
<section id="the-s.-rm.-m.-chettiar-family-banking-industry-education-and-politics" class="level2">
<h2 class="anchored" data-anchor-id="the-s.-rm.-m.-chettiar-family-banking-industry-education-and-politics">The S. Rm. M. Chettiar Family: Banking, Industry, Education, and Politics</h2>
<p>The S. Rm. M. family of Kanadukathan is one of the example. In this, I’d like to explore occupation, generational wealth, and the transformation of the family across different centuries. In their family’s lineage - We notice how they transitioned from early salt traders to become merchant bankers, industrialists and philanthropists of Tamil Nadu.</p>
<section id="branches-of-the-family" class="level3">
<h3 class="anchored" data-anchor-id="branches-of-the-family">Branches of the Family</h3>
<div class="family-table">
<div id="tbl-branches" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[22,26,52]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-branches-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Branches of the S. Rm. M. family and their significance
</figcaption>
<div aria-describedby="tbl-branches-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 26%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Branch / person</th>
<th style="text-align: left;">Main occupation &amp; activity</th>
<th style="text-align: left;">Institutional / financial significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Sathappa Ramanatha Muthiah Chettiar</strong></td>
<td style="text-align: left;">Merchant-banker, philanthropist, patriarch</td>
<td style="text-align: left;">The Patriarch of the Family: capital accumulated through trade, banking, and overseas networks, then converted into temple, choultry, and public philanthropy.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>S. Rm. M. Ramaswami Chettiar</strong></td>
<td style="text-align: left;">Banker, businessman, public figure</td>
<td style="text-align: left;">Associated with early Indian-owned banking and the rise of Indian Bank after the collapse of Arbuthnot Bank.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>S. Rm. M. Annamalai Chettiar</strong></td>
<td style="text-align: left;">Banker, industrialist, educationist, philanthropist</td>
<td style="text-align: left;">Founder of Annamalai University in 1929; associated with Indian Bank and the Imperial Bank; helped convert Chettiar wealth into higher education, Tamil culture, and public institutions <span class="citation" data-cites="annamalai_university_about chettinad_promoters"><a href="#ref-annamalai_university_about" role="doc-biblioref">[15]</a>, <a href="#ref-chettinad_promoters" role="doc-biblioref">[16]</a></span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>M. A. Muthiah Chettiar</strong></td>
<td style="text-align: left;">Banker, educationist, politician, civic leader</td>
<td style="text-align: left;">First Mayor of Madras after the restoration of the mayoralty; associated with Annamalai University, Tamil Isai, public administration, and educational expansion <span class="citation" data-cites="chettinad_promoters"><a href="#ref-chettinad_promoters" role="doc-biblioref">[16]</a></span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>M. A. M. Ramaswamy</strong></td>
<td style="text-align: left;">Industrialist, politician, horse-racing patron</td>
<td style="text-align: left;">Led the Chettinad Group; linked to cement, education, healthcare, and institutional philanthropy. The Chettinad education network today spans medicine, dentistry, engineering, law, architecture, nursing, pharmacy, and allied health <span class="citation" data-cites="chettinad_education_group"><a href="#ref-chettinad_education_group" role="doc-biblioref">[17]</a></span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>M. Ct. Muthiah Chettiar</strong></td>
<td style="text-align: left;">Banker, businessman, philanthropist</td>
<td style="text-align: left;">Director of Indian Bank, South Indian Chamber of Commerce figure, public philanthropist, and father of M.Ct.M. Chidambaram Chettiar <span class="citation" data-cites="mct_muthiah_lifesketch"><a href="#ref-mct_muthiah_lifesketch" role="doc-biblioref">[18]</a></span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>M. Ct. M. Chidambaram Chettiar</strong></td>
<td style="text-align: left;">Banker, insurer, industrialist</td>
<td style="text-align: left;">Founded Indian Overseas Bank in 1937 to specialize in foreign exchange and overseas banking; IOB began simultaneously in Karaikudi, Chennai, and Rangoon, later expanding to Penang. Also associated with United India insurance ventures and Travancore Rayons <span class="citation" data-cites="iob_genesis mctm_inspiration"><a href="#ref-iob_genesis" role="doc-biblioref">[19]</a>, <a href="#ref-mctm_inspiration" role="doc-biblioref">[20]</a></span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>M. Ct. P. Chidambaram / M.Ct. branch</strong></td>
<td style="text-align: left;">Education, trusts, business, diplomacy</td>
<td style="text-align: left;">Later family members managed schools, trusts, trading and investment companies, and public-facing institutions such as M.Ct.M. Chidambaram Chettyar schools <span class="citation" data-cites="mctm_management"><a href="#ref-mctm_management" role="doc-biblioref">[21]</a></span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>M. A. Chidambaram</strong></td>
<td style="text-align: left;">Industrialist, sports administrator, civic figure</td>
<td style="text-align: left;">Founder of SPIC, one of South India’s important fertilizer and petrochemical companies; also a major cricket administrator, remembered through the M. A. Chidambaram Stadium.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>A. C. Muthiah</strong></td>
<td style="text-align: left;">Industrialist, cricket administrator</td>
<td style="text-align: left;">Led SPIC-related industrial interests and later served as BCCI president; represents the branch’s movement from mercantile finance into modern corporate industry.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Ashwin Muthiah</strong></td>
<td style="text-align: left;">Industrialist, chairman / founder of AM International</td>
<td style="text-align: left;">AM International oversees a roughly $2-billion portfolio across fertilizers and petrochemicals, including SPIC, Manali Petrochemicals, Tamil Nadu Petroproducts, and Tuticorin Alkali Chemicals &amp; Fertilizers <span class="citation" data-cites="toi_ashwin_muthiah_2026"><a href="#ref-toi_ashwin_muthiah_2026" role="doc-biblioref">[22]</a></span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Lakshmi Achi → P. Chidambaram → Karti Chidambaram</strong></td>
<td style="text-align: left;">Law, politics, Parliament, finance ministry</td>
<td style="text-align: left;">Shows the family’s movement into modern law and national politics. P. Chidambaram became Union Finance Minister and Home Minister; Karti Chidambaram represents Sivaganga in Parliament.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p>In terms of finances and wealth, their capital moved through several stages, private merchant banking, overseas credit networks, modern banks and insurance, industry and education, and public life and politics.</p>
</section>
</section>
<section id="generational-diagram" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="generational-diagram">Generational Diagram</h2>
<div class="column-screen-inset">
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "theme": "base",
  "themeVariables": {
    "fontFamily": "Georgia, 'Times New Roman', serif",
    "fontSize": "14px",
    "lineColor": "#8a7560"
  },
  "flowchart": { "htmlLabels": true, "nodeSpacing": 28, "rankSpacing": 85, "curve": "basis" }
}}%%
flowchart TB

    G0["&lt;b&gt;S. Rm. Muthiah Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;merchant-banker; patriarch&lt;/i&gt;&lt;br/&gt;Chettiar moneylending network:&lt;br/&gt;Burma · Malaya · Ceylon"]

    G1A["&lt;b&gt;S. Rm. M. Chidambaram Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;M.Ct. branch&lt;/i&gt;"]
    G1B["&lt;b&gt;S. Rm. M. Ramaswami Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;co-founder, Indian Bank (1907)&lt;/i&gt;"]
    G1C["&lt;b&gt;S. Rm. M. Annamalai Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;Raja of Chettinad&lt;/i&gt;&lt;br/&gt;Indian Bank · United India Insurance&lt;br/&gt;Annamalai University (1929)&lt;br/&gt;charity &amp;gt; ₹1 cr (~$3M, 1940s)"]

    G0 --&gt; G1A &amp; G1B &amp; G1C

    G2A["&lt;b&gt;M. Ct. Muthiah Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;banker; Imperial Legislative Council&lt;/i&gt;"]
    G2B["&lt;b&gt;M. Ct. Pethachi Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;zamindari / M.Ct. branch&lt;/i&gt;"]
    G2C["&lt;b&gt;R. Ramanathan Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;public life&lt;/i&gt;"]
    G2D["&lt;b&gt;M. A. Muthiah Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;1st Mayor of Madras; Tamil Isai&lt;/i&gt;&lt;br/&gt;Chettinad Group, Raja title"]
    G2E["&lt;b&gt;M. A. Ramanathan Chettiar&lt;/b&gt;"]
    G2F["&lt;b&gt;M. A. Chidambaram&lt;/b&gt;&lt;br/&gt;&lt;i&gt;SPIC; Chepauk stadium; cricket&lt;/i&gt;"]
    G2G["&lt;b&gt;Lakshmi Achi&lt;/b&gt;&lt;br/&gt;&lt;i&gt;mother of P. Chidambaram&lt;/i&gt;"]

    G1A --&gt; G2A &amp; G2B
    G1B --&gt; G2C
    G1C --&gt; G2D &amp; G2E &amp; G2F &amp; G2G

    G3A["&lt;b&gt;M. Ct. M. Chidambaram Chettiar&lt;/b&gt;&lt;br/&gt;&lt;i&gt;founder, Indian Overseas Bank (1937)&lt;/i&gt;&lt;br/&gt;United India insurance · d. 1954"]
    G3B["&lt;b&gt;M. Ct. P. Chidambaram&lt;/b&gt;&lt;br/&gt;&lt;i&gt;education, trusts, business&lt;/i&gt;"]
    G3C["&lt;b&gt;M. A. M. Muthiah&lt;/b&gt;&lt;br/&gt;&lt;i&gt;d. 1970, no heirs&lt;/i&gt;"]
    G3D["&lt;b&gt;M. A. M. Ramaswamy&lt;/b&gt;&lt;br/&gt;&lt;i&gt;Chettinad Group; racehorses&lt;/i&gt;&lt;br/&gt;net worth ≈₹1,500 cr (≈$180M)&lt;br/&gt;empire ≈₹15,000 cr (≈$1.8B)"]
    G3E["&lt;b&gt;A. C. Muthiah&lt;/b&gt;&lt;br/&gt;&lt;i&gt;SPIC chairman; BCCI president&lt;/i&gt;"]
    G3F["&lt;b&gt;P. Chidambaram&lt;/b&gt;&lt;br/&gt;&lt;i&gt;Union Finance / Home Minister&lt;/i&gt;&lt;br/&gt;assets ₹95.66 cr, 2014 (~$11M)"]

    G2A --&gt; G3A
    G2B --&gt; G3B
    G2D --&gt; G3C &amp; G3D
    G2F --&gt; G3E
    G2G --&gt; G3F

    G4A["&lt;b&gt;M. Ct. Muthiah&lt;/b&gt;"]
    G4B["&lt;b&gt;M. Ct. Pethachi&lt;/b&gt;"]
    G4C["&lt;b&gt;M. A. M. M. Annamalai&lt;/b&gt;"]
    G4D["&lt;b&gt;M. A. M. R. Muthiah&lt;/b&gt;&lt;br/&gt;&lt;i&gt;Chettinad Cement; adopted heir&lt;/i&gt;&lt;br/&gt;turnover ₹60 cr → ₹4,000 cr"]
    G4E["&lt;b&gt;Ashwin Muthiah&lt;/b&gt;&lt;br/&gt;&lt;i&gt;AM International Holdings&lt;/i&gt;&lt;br/&gt;~$2B group (Singapore-based)"]
    G4F["&lt;b&gt;Karti Chidambaram&lt;/b&gt;&lt;br/&gt;&lt;i&gt;MP, Sivaganga&lt;/i&gt;&lt;br/&gt;assets ₹79.37 cr, 2019 (~$10M)"]

    G3A --&gt; G4A
    G3B --&gt; G4B
    G3C --&gt; G4C
    G3D --&gt; G4D
    G3E --&gt; G4E
    G3F --&gt; G4F

    classDef gen0 fill:#5c4433,stroke:#3f2e22,color:#f3f2e8,stroke-width:1.5px;
    classDef gen1 fill:#7a3b2e,stroke:#5a2a20,color:#f6efe9,stroke-width:1px;
    classDef gen2 fill:#a8512f,stroke:#7e3c22,color:#fff5ee,stroke-width:1px;
    classDef gen3 fill:#c2873d,stroke:#946328,color:#2e2a25,stroke-width:1px;
    classDef gen4 fill:#e3cfa6,stroke:#b89a63,color:#2e2a25,stroke-width:1px;

    class G0 gen0;
    class G1A,G1B,G1C gen1;
    class G2A,G2B,G2C,G2D,G2E,G2F,G2G gen2;
    class G3A,G3B,G3C,G3D,G3E,G3F gen3;
    class G4A,G4B,G4C,G4D,G4E,G4F gen4;
</pre>
</div>
<p></p><figcaption> Five generations of the S. Rm. M. Chettiar family, from the patriarch’s overseas moneylending network to modern banking, industry, and national politics. Wealth and asset figures are approximate.</figcaption> </figure><p></p>
</div>
</div>
</div>
</div>
<p>The above is only approximate for the wealth and asset information presented. Current data may vary depending on many factors. Please use only the information provided in as approximate variables in documents for any calculations or estimations.</p>
</section>
</section>
<section id="related-earlier-posts-on-caste" class="level1">
<h1>Related Earlier Posts on Caste</h1>
<ol>
<li style="margin-bottom: 1.25rem;">
<a href="https://rickrejeleene.me/Tamil/posts/2015-08-10-Caste-System-India/index.html"><strong>The Modern Caste System in Tamil Nadu</strong></a><br> <strong>Direct link: <a style="overflow-wrap:anywhere;" href="https://rickrejeleene.me/Tamil/posts/2015-08-10-Caste-System-India/index.html">https://rickrejeleene.me/Tamil/posts/2015-08-10-Caste-System-India/index.html</a></strong>
</li>
<li style="margin-bottom: 1.25rem;">
<a href="https://rickrejeleene.me/Tamil/posts/2025-05-28-castes-in-india-ambedkar/index.html"><strong>Castes in India: Their Mechanism, Genesis and Development by B.R. Ambedkar</strong></a><br> <strong>Direct link: <a style="overflow-wrap:anywhere;" href="https://rickrejeleene.me/Tamil/posts/2025-05-28-castes-in-india-ambedkar/index.html">https://rickrejeleene.me/Tamil/posts/2025-05-28-castes-in-india-ambedkar/index.html</a></strong>
</li>
<li style="margin-bottom: 1.25rem;">
<a href="https://rickrejeleene.me/Tamil/posts/2025-08-14-Caste-System-Anthropologist/index.html"><strong>Caste in Tamil Nadu by Anthropologist Diane P. Mines</strong></a><br> <strong>Direct link: <a style="overflow-wrap:anywhere;" href="https://rickrejeleene.me/Tamil/posts/2025-08-14-Caste-System-Anthropologist/index.html">https://rickrejeleene.me/Tamil/posts/2025-08-14-Caste-System-Anthropologist/index.html</a></strong>
</li>
<li style="margin-bottom: 1.25rem;">
<a href="https://rickrejeleene.me/Tamil/posts/2025-08-14-Kallar-Caste/index.html"><strong>Thevar Caste: A Social Group in Tamil Nadu</strong></a><br> <strong>Direct link: <a style="overflow-wrap:anywhere;" href="https://rickrejeleene.me/Tamil/posts/2025-08-14-Kallar-Caste/index.html">https://rickrejeleene.me/Tamil/posts/2025-08-14-Kallar-Caste/index.html</a></strong>
</li>
<li style="margin-bottom: 1.25rem;">
<a href="https://rickrejeleene.me/Tamil/posts/2025-08-19-Tamil-Brahmins/index.html"><strong>Tamil Brahmins: From Village Priests to Software Engineers and Industrialists</strong></a><br> <strong>Direct link: <a style="overflow-wrap:anywhere;" href="https://rickrejeleene.me/Tamil/posts/2025-08-19-Tamil-Brahmins/index.html">https://rickrejeleene.me/Tamil/posts/2025-08-19-Tamil-Brahmins/index.html</a></strong>
</li>
<li style="margin-bottom: 1.25rem;">
<a href="https://rickrejeleene.me/Tamil/posts/2025-08-29-Nadar/index.html"><strong>Nadars: From Palm Trees to Entrepreneurs and One of Tamil Nadu’s Wealthiest Social Groups</strong></a><br> <strong>Direct link: <a style="overflow-wrap:anywhere;" href="https://rickrejeleene.me/Tamil/posts/2025-08-29-Nadar/index.html">https://rickrejeleene.me/Tamil/posts/2025-08-29-Nadar/index.html</a></strong>
</li>
<li style="margin-bottom: 1.25rem;">
<a href="https://rickrejeleene.me/Tamil/posts/2025-10-10-Kongu/index.html"><strong>Kongu Region of Tamil Nadu</strong></a><br> <strong>Direct link: <a style="overflow-wrap:anywhere;" href="https://rickrejeleene.me/Tamil/posts/2025-10-10-Kongu/index.html">https://rickrejeleene.me/Tamil/posts/2025-10-10-Kongu/index.html</a></strong>
</li>
<li style="margin-bottom: 1.25rem;">
<a href="https://rickrejeleene.me/Tamil/posts/2025-05-10-caste-nagarathar/index.html"><strong>Caste Endogamy and Missed Opportunities to Develop the Financial Sector</strong></a><br> <strong>Direct link: <a style="overflow-wrap:anywhere;" href="https://rickrejeleene.me/Tamil/posts/2025-05-10-caste-nagarathar/index.html">https://rickrejeleene.me/Tamil/posts/2025-05-10-caste-nagarathar/index.html</a></strong>
</li>
</ol>
<style>
#refs,
#refs.references,
.references,
.csl-bib-body,
div:has(> #refs),
section:has(#refs) {
  background-color: transparent !important;
  background: transparent !important;
  border: 0 !important;
  box-shadow: none !important;
}
</style>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-thurston1909" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">E. Thurston and K. Rangachari, <em><a href="https://www.gutenberg.org/cache/epub/42995/pg42995-images.html">Castes and tribes of southern india</a></em>, vol. 5. Madras: Government Press, 1909.</div>
</div>
<div id="ref-rudner1989" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">D. W. Rudner, <span>“Banker’s trust and the culture of banking among the nattukottai chettiars of colonial south india,”</span> <em>Modern Asian Studies</em>, vol. 23, no. 3, pp. 417–458, 1989, doi: <a href="https://doi.org/10.1017/S0026749X00009501">10.1017/S0026749X00009501</a>.</div>
</div>
<div id="ref-mahadevan1976" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">R. Mahadevan, <span>“The origin and growth of entrepreneurship in the nattukottai chettiar community of tamilnadu, 1880–1930,”</span> M.Phil. thesis, Jawaharlal Nehru University, New Delhi, 1976.</div>
</div>
<div id="ref-muthiah_chettiar_heritage" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">S. Muthiah, M. Meyappan, and V. Ramaswamy, <em>The chettiar heritage</em>, 2nd ed. Chennai, India: Kottaiyur Chettiar Heritage Trust, 2018.</div>
</div>
<div id="ref-Nishimura1998GenderKinshipPropertyRights" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">Y. Nishimura, <em>Gender, kinship and property rights: Nagarattar womanhood in south india</em>. Delhi: Oxford University Press, 1998.</div>
</div>
<div id="ref-rudner1994caste" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline">D. W. Rudner, <em>Caste and capitalism in colonial india: The nattukottai chettiars</em>. Berkeley; Los Angeles: University of California Press, 1994.</div>
</div>
<div id="ref-kuncheria_chettiars" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div><div class="csl-right-inline">C. J. Kuncheria, <span>“<a href="https://www.academia.edu/5904081/Empire_and_Indian_Merchant_Networks_The_Case_of_the_Chettiars">Empire and indian merchant networks: The case of the chettiars</a>,”</span> 2014.</div>
</div>
<div id="ref-punitha2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[8] </div><div class="csl-right-inline">A. Punitha, <span>“<a href="https://sttemplelibrary.com/uploads/Nattukottai%20Chettiar%20Business%20Practices%20and%20Perspectives%20by%20A%20Punitha.pdf">Nattukottai chettiars: Business practices and perspectives</a>,”</span> PhD thesis, Pondicherry University, 2016.</div>
</div>
<div id="ref-jain1929" class="csl-entry" role="listitem">
<div class="csl-left-margin">[9] </div><div class="csl-right-inline">L. C. Jain, <em>Indigenous banking in india</em>. London: Macmillan, 1929.</div>
</div>
<div id="ref-weerasooria1973" class="csl-entry" role="listitem">
<div class="csl-left-margin">[10] </div><div class="csl-right-inline">W. S. Weerasooria, <em>The nattukottai chettiar: Merchant bankers in ceylon</em>. Dehiwala, Sri Lanka: Tisara Prakasakayo, 1973.</div>
</div>
<div id="ref-subramaniam2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[11] </div><div class="csl-right-inline">V. A. Subramaniam and T. Athiyaman, <span>“Role of nattukottai chettiars in the financial history of sri lanka,”</span> <em>International Journal of Business Quantitative Economics and Applied Management Research</em>, vol. 3, no. 5, pp. 14–23, 2016.</div>
</div>
<div id="ref-unesco2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">[12] </div><div class="csl-right-inline">UNESCO World Heritage Centre, <span>“Chettinad, village clusters of the tamil merchants.”</span> 2014, [Online]. Available: <a href="https://whc.unesco.org/en/tentativelists/5920/">https://whc.unesco.org/en/tentativelists/5920/</a>.</div>
</div>
<div id="ref-ito1966" class="csl-entry" role="listitem">
<div class="csl-left-margin">[13] </div><div class="csl-right-inline">S. Ito, <span>“A note on the <span>‘business combine’</span> in india: With special reference to the nattukottai chettiars,”</span> <em>The Developing Economies</em>, vol. 4, no. 3, pp. 367–380, 1966.</div>
</div>
<div id="ref-rejeleene2025tamillibrary" class="csl-entry" role="listitem">
<div class="csl-left-margin">[14] </div><div class="csl-right-inline">R. Rejeleene, <span>“A tamil library stands testament of capitalism.”</span> 2025, [Online]. Available: <a href="https://rickrejeleene.me/Tamil/posts/2025-04-06-Tamil-Capitalism/index.html">https://rickrejeleene.me/Tamil/posts/2025-04-06-Tamil-Capitalism/index.html</a>.</div>
</div>
<div id="ref-annamalai_university_about" class="csl-entry" role="listitem">
<div class="csl-left-margin">[15] </div><div class="csl-right-inline">Annamalai University, <span>“About the university.”</span> 2026, [Online]. Available: <a href="https://annamalaiuniversity.ac.in/about_university.php">https://annamalaiuniversity.ac.in/about_university.php</a>.</div>
</div>
<div id="ref-chettinad_promoters" class="csl-entry" role="listitem">
<div class="csl-left-margin">[16] </div><div class="csl-right-inline">Chettinad Group, <span>“Promoters.”</span> 2026, [Online]. Available: <a href="https://www.chettinad.com/promoters.php">https://www.chettinad.com/promoters.php</a>.</div>
</div>
<div id="ref-chettinad_education_group" class="csl-entry" role="listitem">
<div class="csl-left-margin">[17] </div><div class="csl-right-inline">Chettinad Education and Services, <span>“The group.”</span> 2026, [Online]. Available: <a href="https://www.chettinadeducation.org/the-group/">https://www.chettinadeducation.org/the-group/</a>.</div>
</div>
<div id="ref-mct_muthiah_lifesketch" class="csl-entry" role="listitem">
<div class="csl-left-margin">[18] </div><div class="csl-right-inline">Hindu High School, <span>“Life sketches of sir m.ct. Muthiah chettiar.”</span> 2026, [Online]. Available: <a href="https://hinduhighschool.com/lifesketches/life_sketches6.htm">https://hinduhighschool.com/lifesketches/life_sketches6.htm</a>.</div>
</div>
<div id="ref-iob_genesis" class="csl-entry" role="listitem">
<div class="csl-left-margin">[19] </div><div class="csl-right-inline">Indian Overseas Bank, <span>“Genesis.”</span> 2026, [Online]. Available: <a href="https://www.iob.bank.in/en/genesis">https://www.iob.bank.in/en/genesis</a>.</div>
</div>
<div id="ref-mctm_inspiration" class="csl-entry" role="listitem">
<div class="csl-left-margin">[20] </div><div class="csl-right-inline">M.Ct.M. Chidambaram Chettyar International School, <span>“Our inspiration.”</span> 2026, [Online]. Available: <a href="https://mctminternational.com/our-inspiration/">https://mctminternational.com/our-inspiration/</a>.</div>
</div>
<div id="ref-mctm_management" class="csl-entry" role="listitem">
<div class="csl-left-margin">[21] </div><div class="csl-right-inline">M.Ct.M. Chidambaram Chettyar International School, <span>“Management.”</span> 2026, [Online]. Available: <a href="https://mctminternational.com/management/">https://mctminternational.com/management/</a>.</div>
</div>
<div id="ref-toi_ashwin_muthiah_2026" class="csl-entry" role="listitem">
<div class="csl-left-margin">[22] </div><div class="csl-right-inline">G. Balachandar, <span>“Institutions must be stronger than individuals,”</span> <em>The Times of India</em>, Feb. 2026, [Online]. Available: <a href="https://timesofindia.indiatimes.com/city/chennai/institutions-must-be-stronger-than-individuals/articleshow/128082702.cms">https://timesofindia.indiatimes.com/city/chennai/institutions-must-be-stronger-than-individuals/articleshow/128082702.cms</a>.</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ludwigwittgenstein2\.github\.io\/Tamil\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>