{
  "hash": "524716be78b7c08f6f4344a8c4f04407",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"How do Mobile Phones Work?\"\nsubtitle: \"Networks, Radio, Embedded Systems\"\ndescription: \"A systems-level tutorial explaining how mobile phones work, from cellular networks and voice calls to embedded electronics\"\nauthor: \"Rick Rejeleene\"\ndate: 2026-05-10\ndate-format: \"MMMM D, YYYY\"\nfilters:\n  - d2\ncategories:\n  - Engineering\n  - Tutorial\n  - Electrical Engineering\n  - Electronics\n  - Embedded Systems\n  - Computer Science\n  \nformat:\n  html:\n    css: styles.css\n    toc: true\n    toc-title: \"Contents\"\n    toc-depth: 3\n---\n\n## Introduction: Nokia 1100 Memory\n\nOne of the mobile phones that made a lasting impact on me, my friends, and many people around me was the Nokia 1100.\n\nAt that time, I was in middle school. It never occurred to me to ask: *how does a mobile phone work?*\n*What are the components inside it?* *What would it take to build one?*\n\nThis tutorial starts with that basic engineering question:\n\n> What is inside a mobile phone?  \n> How does it connect to a tower?  \n> How does voice become radio waves?  \n> What happens at each layer of the phone's system?\n\nThe Nokia 1100 became the world's best-selling mobile phone of all time. It reached 250 million units by 2008, holding the record for the best-selling mobile phone of all time. In the early 2000s, this was one of the phones everyone around me appreciated. It was simple, durable, and did the job: it made and received phone calls, and the battery life was long-lasting. While the Nokia 1100 is no longer in production, my goal in this tutorial is to understand how mobile phones work.\n\n## What is a Mobile Phone?\n\nA modern phone is a small, low-power computer that runs an operating system like Android or iOS, runs apps, and has a cellular modem to connect to the mobile network. It is also a radio system that handles cellular calls, Wi-Fi, Bluetooth, GPS, and other wireless communication. All of this is crammed into a thin handheld device that can be used for hours on a single charge.\n\n![Three mini computers in a mobile phone](/images/mobilephone/image1.png){fig-alt=\"A diagram showing three computers within the mobile phone.\"}\n\n## How does a Mobile Phone Work?\n\nA mobile phone is essentially a small, two-way radio that connects to a cellular network so you can talk, text, or use data without wires.\nIt digitizes your voice or data, sends it as radio waves to the nearest cell tower, and then the network routes it to the other phone or to the internet.\n\nThe land is divided into cells, where each cell is served by a tower or base station. \nYour phone always talks to a nearby tower, and as you move, the network hands over your connection smoothly from one cell to the next. \nA mobile phone is not only a radio. It is a system made of cooperating subsystems: computing, radio, power, audio, display, memory, software, and network identity.\n\n## System Layer-View\n\nTo understand mobile phones properly, we need to understand the system in layers. \nEach layer explains one part of the phone.\n\n![System View](/images/mobilephone/protocolview.png){fig-alt=\"System View\"}\n\nA mobile phone combines electronics, software, radio, networking, security, manufacturing, and telecom infrastructure compressed into one handheld device.\n\n## The Three Computing Systems Inside a Phone\n\nWe cannot fully call a mobile phone only a radio, because a mobile phone has three computers within it.\n\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Component</th>\n      <th class=\"voice\">Function</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\"><strong>Application processor</strong></td>\n      <td class=\"voice\">Runs the operating system, draws the screen, handles your taps, and runs apps.</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><strong>Baseband processor / modem</strong></td>\n      <td class=\"voice\">Handles cellular communication, talks to cell towers, manages the radio, and controls cellular protocols and timing.</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><strong>SIM card</strong></td>\n      <td class=\"voice\">Acts as a tiny secure computer. It holds your network identity and a secret cryptographic key that proves you are a legitimate subscriber.</td>\n    </tr>\n  </tbody>\n</table>\nThese three components work together and communicate with each other, yet they are logically separate.\nThe application processor handles the user-facing side of the phone. The baseband processor handles cellular communication. \nThe SIM card provides identity and authentication.\n\n## SIM Card \n\nIn simple terms, the SIM card answers one question for the network:\n\n> Is this phone really allowed to use this mobile service?\n\nThe SIM does this by proving that it knows a secret key. The secret key is stored inside the SIM and also inside the carrier's authentication system. The key itself is never sent over the air. Instead, the network sends a random challenge. The SIM uses its secret key to compute an answer. The carrier computes the same answer on its side. If the answers match, the network accepts the phone.\n\nSo the SIM is not just a memory card. It is a tiny secure computer that stores identity, protects a secret key, and performs cryptographic calculations.\n\n## A Small Code Example: How a SIM Proves Its Identity\n\nThe SIM card has one important job: it proves to the mobile network that the phone belongs to a valid subscriber.\n\nThe SIM does this using a secret key.\n\nThe important rule is:\n\n> The secret key is never sent over the air.\n\nInstead, the network sends the SIM a random challenge. \nThe SIM uses its secret key to calculate an answer.\nThe carrier does the same calculation on its side. \nIf both answers match, the network accepts the phone.\n\nThis is called **challenge-response authentication**.\n\nA simplified version looks like this:\n\n::: {#d288f89b .cell execution_count=1}\n``` {.python .cell-code}\nimport os\nimport hmac\nimport hashlib\n\n# ---------------------------------------------------------\n# 1. The SIM and the carrier both know the same secret key.\n# In a real phone, this key is stored securely inside the SIM.\n# The carrier also stores a copy in its authentication system.\n# ---------------------------------------------------------\n\nsim_secret_key = os.urandom(16)\n\n# ---------------------------------------------------------\n# 2. The network sends a random challenge.\n# This changes every time, so old answers cannot be reused.\n# ---------------------------------------------------------\n\nchallenge = os.urandom(16)\n\n# ---------------------------------------------------------\n# 3. The SIM uses the secret key to compute an answer.\n# ---------------------------------------------------------\n\nsim_answer = hmac.new(\n    sim_secret_key,\n    challenge,\n    hashlib.sha256\n).hexdigest()\n\n# ---------------------------------------------------------\n# 4. The carrier computes the expected answer using its copy\n# of the same secret key.\n# ---------------------------------------------------------\n\ncarrier_expected_answer = hmac.new(\n    sim_secret_key,\n    challenge,\n    hashlib.sha256\n).hexdigest()\n\n# ---------------------------------------------------------\n# 5. If both answers match, the SIM is accepted.\n# ---------------------------------------------------------\n\nprint(\"Network challenge:\", challenge.hex())\nprint(\"SIM answer:\", sim_answer)\nprint(\"Carrier expected answer:\", carrier_expected_answer)\n\nif hmac.compare_digest(sim_answer, carrier_expected_answer):\n    print(\"Authentication successful: SIM is accepted.\")\nelse:\n    print(\"Authentication failed: SIM is rejected.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNetwork challenge: b000ddf6a3dcbac4743a4ca297f71c48\nSIM answer: ac17269404b098b8a2596ba0d46089db08f8cdd0544c39dfe8fcc8a95d2d9f86\nCarrier expected answer: ac17269404b098b8a2596ba0d46089db08f8cdd0544c39dfe8fcc8a95d2d9f86\nAuthentication successful: SIM is accepted.\n```\n:::\n:::\n\n\n## How the SIM Actually Authenticates\n\n\nThe earlier code showed the basic idea: the SIM proves that it knows a secret key without revealing the key.\n\nIn GSM, this secret key is called **Ki**. It is stored inside the SIM and also inside the carrier's authentication system. When the phone connects to the network, the network sends a random challenge called **RAND**.\n\nThe SIM uses **Ki** and **RAND** to calculate a response called **SRES**. The carrier performs the same calculation on its side. If the SIM's response matches the carrier's expected response, the phone is authenticated.\n\n```text\nSIM side:      Ki + RAND → SRES\nCarrier side:  Ki + RAND → expected SRES\n\nIf SRES matches expected SRES:\n    accept the phone\n  ```\n\n### LTE and 5G\n\nLater systems such as LTE and 5G use a stronger method called **AKA**, or **Authentication and Key Agreement**.\n\nOne weakness of GSM is that it mainly authenticates the phone to the network. In other words, the network checks whether the SIM is valid. But GSM does not strongly prove to the phone that the network itself is legitimate. This weakness is one reason fake towers can trick phones into connecting.\n\nLTE improves this by adding **mutual authentication**. The phone proves itself to the network, and the network also proves itself to the phone.\n\n```text\nGSM:\nPhone proves itself to the network.\nLTE and 5G:\nPhone proves itself to the network.\nNetwork also proves itself to the phone.\n```\n\nLTE and 5G also derive stronger temporary session keys. These keys are used to protect communication between the phone and the network. They also include protections against replay attacks, where an attacker records an old authentication message and tries to reuse it later.\n\n5G goes further by protecting the subscriber's long-term identity more carefully. Older systems could expose permanent subscriber identifiers in some situations. 5G reduces this risk by making it harder for attackers to track users based on their permanent identity.\n\nThe basic idea remains the same:\n\n```text\nThe SIM proves identity.\nThe network verifies the SIM.\nBoth sides create temporary keys.\nThe radio connection becomes protected.\n```\n\nThis is why the SIM is not just a memory card. It is a tiny secure computer. It stores identity, protects secret keys, and performs cryptographic calculations that allow the phone to securely join the cellular network.\n\n## Cellular Network\n\nThe basic idea of a cellular network is that land is divided into cells. Each cell is served by a tower or base station. Your phone talks to whichever tower has the best signal, usually the nearest, but not always. As you move, the network hands over your connection smoothly from one cell to the next, often without you noticing. This is the fundamental trick that lets a phone work while you are driving down a highway. Even when you are not making a call, the phone is still quietly connected to the network.\n\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Idle-mode function</th>\n      <th class=\"voice\">Description</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\"><strong>Paging</strong></td>\n      <td class=\"voice\">The phone listens for messages such as: \"Hey phone with this ID, someone is calling you.\"</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><strong>Location update</strong></td>\n      <td class=\"voice\">The phone tells the network which tower it is near, so incoming calls can find it.</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><strong>Message delivery</strong></td>\n      <td class=\"voice\">The phone receives waiting SMS messages and network notifications.</td>\n    </tr>\n  </tbody>\n</table>\n\n## The Shared-Spectrum Problem\n\nYour phone is sharing the airwaves with millions of others. \nEvery cellular standard, (GSM, UMTS, LTE, 5G) is fundamentally a set of clever techniques to make shared radio communication work.\n\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Technique</th>\n      <th class=\"voice\">Description</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\"><strong>Frequency division</strong></td>\n      <td class=\"voice\">The spectrum is divided into channels, like highway lanes.</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><strong>Time division</strong></td>\n      <td class=\"voice\">Within one channel, time is sliced into tiny slots. Your phone transmits briefly, then waits while other phones take their turn.</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><strong>Cell reuse</strong></td>\n      <td class=\"voice\">A tower 20 km away can reuse the same frequencies because radio signals fade with distance.</td>\n    </tr>\n  </tbody>\n</table>\n\nThis is what made cellular communication scale to billions of users.\n\n## When We Make a Call\n\nWhen we make a call, the phone performs a sequence of conversions.\n\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Step</th>\n      <th class=\"voice\">Process</th>\n      <th class=\"sms\">Description</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\">1</td>\n      <td class=\"voice\">Voice becomes electricity</td>\n      <td class=\"sms\">Your voice hits the phone's microphone, which converts sound into an electrical signal.</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">2</td>\n      <td class=\"voice\">Electricity becomes bits</td>\n      <td class=\"sms\">An internal chip converts the analog signal into digital bits and packs them into radio-wave signals.</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">3</td>\n      <td class=\"voice\">Bits become radio waves</td>\n      <td class=\"sms\">The antenna sends the radio signal to the nearest cell tower.</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">4</td>\n      <td class=\"voice\">The process reverses</td>\n      <td class=\"sms\">The recipient's phone converts the digital signal back into sound through the speaker.</td>\n    </tr>\n  </tbody>\n</table>\nThe key components involved include the radio and antenna, microprocessor, operating system, memory, storage, battery, display, sensors, and SIM card.\n\n## A Concrete Example: Dallas to Chennai\n\nAssume you live in Dallas, Texas, and you are going to call your friend in Chennai. \nLet us say you have international calling enabled on your plan.\n\n- **Your number in Dallas:** `+1 214-555-1234`\n- **Your friend's number in Chennai:** `+91 98765 43210`\n\nNow, we might wonder: what is actually happening when the Dallas number calls the Chennai number?\n\nThe answer involves a journey of roughly **13,500 km** that completes in under a second. \nOnce the call connects, your voice makes that same trip in about **150 milliseconds**.\n\n![Path of a call from Dallas to Chennai](/images/mobilephone/DallasChennai.png){fig-alt=\"A diagram showing the path of a call from Dallas to Chennai.\"}\n\n### Step 1: Decoding the Number\n\nThe moment you tap \"call,\" your phone hands the number `+91 98765 43210` to your carrier. \nThe carrier reads it like an address.\n\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Part</th>\n      <th class=\"voice\">Meaning</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\"><code>+91</code></td>\n      <td class=\"voice\">Country code for India</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><code>98765</code></td>\n      <td class=\"voice\">Mobile operator prefix, such as Airtel, Jio, or Vi</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><code>43210</code></td>\n      <td class=\"voice\">The specific subscriber</td>\n    </tr>\n  </tbody>\n</table>\n\nYour carrier's switching center looks at `+91` and immediately knows that this is not a domestic call. \nIt needs to leave the country.\n\n### Step 2: Handoff to an International Gateway\n\nYour call gets routed to an **international gateway**, typically located in major hub cities such as New York, Miami, or Los Angeles. \nThese gateways are operated by carriers such as Tata Communications, BT, and Orange, which own or lease undersea cable capacity.\nThe gateway plans the cheapest and fastest route to India based on existing peering agreements.\n\n### Step 3: Crossing the Planet Through Glass\n\nYour call does not usually go through satellite. Almost all international voice traffic travels through **undersea fiber optic cables** lying on the ocean floor.\n\nFrom the United States to India, a typical path might look like this:\n\n::: {.route-diagram}\n\n```{.d2}\ndirection: right\n\nus: \"US East Coast\\nAtlantic\" {\n  shape: rectangle\n  width: 150\n  height: 58\n  style.fill: \"#dbeafe\"\n  style.font-size: 13\n  style.bold: true\n}\n\nuk: \"UK\\nEurope\" {\n  shape: rectangle\n  width: 130\n  height: 58\n  style.fill: \"#e0e7ff\"\n  style.font-size: 13\n  style.bold: true\n}\n\negypt: \"Egypt\\nSuez / Red Sea\" {\n  shape: rectangle\n  width: 160\n  height: 58\n  style.fill: \"#fde68a\"\n  style.font-size: 13\n  style.bold: true\n}\n\nocean: \"Indian Ocean\\nCables\" {\n  shape: rectangle\n  width: 160\n  height: 58\n  style.fill: \"#cffafe\"\n  style.font-size: 13\n  style.bold: true\n}\n\nindia: \"Mumbai\\nor Chennai\" {\n  shape: rectangle\n  width: 140\n  height: 58\n  style.fill: \"#dcfce7\"\n  style.font-size: 13\n  style.bold: true\n}\n\nus -> uk {\n  style.stroke-width: 2\n}\n\nuk -> egypt {\n  style.stroke-width: 2\n}\n\negypt -> ocean {\n  style.stroke-width: 2\n}\n\nocean -> india {\n  style.stroke-width: 2\n}\n```\n\n:::\n\nInside those cables, your voice is represented as laser pulses flickering on and off billions of times per second through a glass thread thinner than a human hair.\n\n### Step 4: Arriving in India\n\nThe call reaches an Indian gateway carrier, which recognizes `98765` as a prefix belonging to a mobile operator, for example Airtel. \nIt then hands the call to Airtel's network.\n\nAirtel's switching center looks up subscriber `+91 98765 43210` in its database and asks:\n\n> Which tower did this phone last check in with?\n\nEvery cell phone, when powered on, registers with the nearest tower. \nSo Airtel already knows that your friend's phone is connected to a specific tower, for example in T. Nagar, Chennai.\n\n### Step 5: The Phone Rings\n\nAirtel's network sends a **paging message** to that Chennai tower:\n\n> Phone `98765 43210`, you have an incoming call from `+1 214-555-1234`.\n\nYour friend's phone, which has been quietly listening for paging messages, hears its own ID. \nThe screen lights up. The ringtone plays. Caller ID shows your number.\n\nMeanwhile, in Dallas, you hear a ringback tone. \nThat \"ring ring\" is not usually the actual sound of his phone ringing. \nIt is a tone generated by the network to tell you that the call is being attempted.\n\n### Step 6: He Picks Up\n\nHe taps accept. His phone tells the Chennai tower the call has been accepted. That confirmation flows back across the same path in reverse:\n\n::: {.wide-diagram}\n\n```{.d2}\ndirection: right\n\nfriend: \"Friend\\nChennai\" {\n  shape: rectangle\n  width: 260\n  height: 130\n  style.fill: \"#fef3c7\"\n  style.font-size: 28\n  style.bold: true\n}\n\nairtel: \"Airtel\\nNetwork\" {\n  shape: rectangle\n  width: 260\n  height: 130\n  style.fill: \"#f8fafc\"\n  style.font-size: 28\n  style.bold: true\n}\n\nintl: \"Undersea\\nFiber\" {\n  shape: rectangle\n  width: 260\n  height: 130\n  style.fill: \"#e0e7ff\"\n  style.font-size: 28\n  style.bold: true\n}\n\ncarrier: \"Your\\nCarrier\" {\n  shape: rectangle\n  width: 260\n  height: 130\n  style.fill: \"#f8fafc\"\n  style.font-size: 28\n  style.bold: true\n}\n\nyou: \"You\\nDallas\" {\n  shape: rectangle\n  width: 260\n  height: 130\n  style.fill: \"#fef3c7\"\n  style.font-size: 28\n  style.bold: true\n}\n\nfriend -> airtel -> intl -> carrier -> you: \"call accepted\" {\n  style.stroke-width: 4\n  style.font-size: 22\n}\n```\n:::\n\n**~200 ms** from his tap to your phone hearing \"call connected.\"\n\n### Step 7: Voice Transmission\n\nNow the conversation flows. Each \"Hello\" makes the journey through several layers:\n\n1. His microphone captures the sound.\n2. An ADC samples it 8,000 times per second.\n3. A voice codec compresses it to approximately 13 kbps.\n4. The signal is encrypted and error-corrected.\n5. It travels by radio to the Chennai tower.\n6. It travels by fiber to Airtel's core network.\n7. It passes through undersea cables to the United States.\n8. It reaches your carrier and then your Dallas tower.\n9. It travels by radio to your phone.\n10. It is decoded, decrypted, and converted back to sound.\n11. Your speaker plays \"Hello.\"\n\nADC stands for **Analog-to-Digital Converter**. Kbps means **kilobits per second**.\nThe total delay is about **150–250 milliseconds** from his lips to your ear.\n\n### Why Is This So Fast?\n\nThere are three main reasons:\n\n1. **Light is incredibly fast.** Even halfway around the planet, light through fiber takes only about 100 ms.\n2. **The route is pre-built.** Cables, towers, and routing tables were established years ago. Your call does not find a path from scratch; it uses an existing path.\n3. **Both phones are already logged in.** The network already knows which tower each phone is near, so connecting the call is a lookup problem, not a search problem.\n\nWhat was most surprising to me is the infrastructure, especially fiber optic cables under the ocean. \nMany carriers operate them, and they have peering agreements to route traffic across the world. \n\nThe above discussion gives a system-level and network-level overview of how a mobile phone works.\nNext, we look at the phone from the bottom up, starting with the physical components and building our way up to the network.\n\n## A Bottom-Up View\n\nNow let's flip the view. Let's start at the very bottom, with electrons and transistors, and build our way up.\nThis is how engineers actually think about a phone. \n\nTo make this concrete, we'll trace two examples all the way through:\n\n1. **A Voice Call** from Dallas to Chennai.\n2. **A Text Message** to the same person.\n\n### Example 1: Calling Chennai\n\nYou're in Dallas, dialing **+91 98765 43210** to reach your friend in Chennai. \nHe picks up. You say \"Hello.\" He hears it. Let's follow this all the way from the atoms to the cell tower, layer by layer.\n\n#### Layer 1: Physics, your voice as pressure waves\n\nYou speak the word \"Hello.\" Your vocal cords vibrate at roughly 100–250 Hz, pushing air molecules in tiny waves of pressure. \nThese waves travel about 5 cm to the microphone hole on the bottom of the Nokia 3210.\n\nInside that hole sits a **MEMS microphone**: a chip the size of a grain of rice with a thin silicon membrane suspended over a backplate. \nAs pressure waves hit the membrane, it flexes inward and outward by a few nanometers. \nThe gap between the membrane and the backplate forms a tiny capacitor whose capacitance changes with the flex.\nThere are no bits yet. There's just air, then a wiggling membrane, then a wiggling capacitance.\n\n#### Layer 2: Components, converting wiggle to voltage\n\nThe MEMS microphone has a small built-in amplifier that converts the changing capacitance into a changing voltage. \nThe voltage swings between about 0 and 1 volt, mirroring the pressure of the sound wave.\n\nThis analog voltage flows along a PCB trace into the Unisoc T107's audio input pin, where it meets an **Analog-to-Digital Converter (ADC)**.\n\nThe ADC samples the voltage **8,000 times per second** and assigns each sample a number between 0 and 65,535 (a 16-bit value). \nThis rate — 8 kHz, 16-bit — is the standard for telephone-grade voice. It's enough to capture every vocal sound humans make, and not a hertz more.\nWe've crossed the boundary. Sound is now numbers.\n\n#### Layer 3: Digital logic, the audio stream\n\nEight thousand 16-bit samples per second is **128 kbps** of raw audio data. This is too much to transmit over a cellular channel, so the chip's audio hardware passes the stream into a **DSP** (Digital Signal Processor) inside the same Unisoc T107 chip.\n\nThe DSP is a special-purpose CPU built to do math on streams of numbers very fast. \nIt runs the **AMR codec** (Adaptive Multi-Rate, the standard for GSM and early LTE voice). \nThe codec analyzes the audio and:\n\n- Models your vocal tract as a mathematical filter\n- Throws away frequencies you don't produce\n- Encodes the residual as a compact stream of parameters\n\nAfter compression, the audio stream is down to about **12.2 kbps** — roughly a tenth of its raw size. \nThe shape of \"Hello\" is now a sequence of numbers describing how to reconstruct it later.\n\n#### Layer 4: CPU and protocol stack\n\nThe compressed audio enters the **baseband processor** — the same Unisoc T107, but a different functional block. \nThe baseband runs a real-time operating system whose entire job is to speak the cellular protocol.\n\nThe baseband does several things:\n\n1. **Frames** the audio into packets of the size the network expects.\n2. **Adds error-correction codes** — extra bits that let the tower recover the data even if some bits get garbled in transit.\n3. **Encrypts** the packets using the cipher key the SIM negotiated when the phone last authenticated.\n4. **Schedules** the packets for transmission in your phone's assigned time slot on the radio channel.\n\nEach step here is implemented in code running on a tiny CPU inside the modem block. \nThe code was written and certified by Unisoc, locked in firmware, and never updated by the user.\n\n#### Layer 5: Radio, turning bits into electromagnetic waves\n\nThe encrypted, error corrected packets head into the radio circuitry.\n\nA **modulator** takes the bit stream and maps it onto a carrier wave — a pure 1,800 MHz oscillation generated by a **frequency synthesizer**. \nThe mapping is done using QAM (Quadrature Amplitude Modulation), where each combination of bits picks a specific amplitude and phase of the carrier.\n\nThe modulated signal, still tiny, microvolt-level, passes through:\n\n- A **mixer** that lifts it to the exact frequency of your assigned LTE band\n- A **filter** that cleans out unwanted frequencies\n- A **power amplifier (PA)** that boosts it from microwatts to about 200 milliwatts\n- An **antenna switch** that routes it to the correct antenna for the band\n- The **antenna** itself — a printed metal trace on the PCB, tuned to about 4 cm length for 1,800 MHz\n\nThe antenna radiates the signal as electromagnetic waves into the air. \nAbout 200 milliwatts of radio power launches into all directions at the speed of light.\n\n#### Layer 6: The cell tower\n\nA few hundred meters to a few kilometers away, a cell tower's antenna receives the wave. The tower's electronics reverse everything your phone just did: amplify, filter, mix down, demodulate, decrypt the outer transport layer. Your audio packets are now sitting inside your carrier's network as digital data. From here, they travel as pure information, never as sound again, until they reach Chennai.\n\n#### Layer 7: The journey through the network\n\nYour packets travel from the Dallas tower through your carrier's fiber to a switching center, then to an international gateway in (say) New York, then onto an undersea fiber optic cable. In the fiber, your \"Hello\" is now **patterns of laser light** flickering through a glass thread on the ocean floor. The light pulses travel at roughly 200,000 km per second through the glass, hop through repeaters and undersea amplifiers, and arrive in Mumbai about 100–150 milliseconds after they left Dallas.\n\nFrom Mumbai the data flows on terrestrial fiber to Chennai, into Airtel's switching center, then to the cell tower in T. Nagar that your friend's phone last registered with.\n\n#### Layer 8: His phone, in reverse\n\nThe Chennai tower transmits a radio signal to your friend's phone. \nFrom here, every layer happens *in reverse*:\n\n- Antenna receives the wave\n- Low-Noise Amplifier (LNA) boosts the tiny signal without adding noise\n- Mixer drops it back to baseband frequency\n- Demodulator turns the wave into bits\n- Modem decrypts and error-corrects\n- DSP runs the AMR codec in **decode** mode, reconstructing audio samples\n- DAC (Digital-to-Analog Converter) turns the samples back into a voltage waveform\n- A small speaker amplifier drives the earpiece speaker\n- The speaker membrane vibrates, pushing air molecules\n- Air pressure waves hit his eardrum\n- He hears \"Hello\"\n\n![the voice call layer stack](/images/mobilephone/voicelayer.png){fig-alt=\"The voice call layer stack.\"}\n\n#### The whole journey\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Layer</th>\n      <th class=\"voice\">What's moving</th>\n      <th class=\"sms\">Form</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\">1. Vocal cords</td>\n      <td class=\"voice\">Air pressure</td>\n      <td class=\"sms\">Sound waves in your room</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">2. Microphone</td>\n      <td class=\"voice\">Voltage</td>\n      <td class=\"sms\">Analog electrical signal</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">3. ADC</td>\n      <td class=\"voice\">Numbers</td>\n      <td class=\"sms\">128 kbps digital stream</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">4. Codec</td>\n      <td class=\"voice\">Compressed numbers</td>\n      <td class=\"sms\">12.2 kbps encoded stream</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">5. Modem</td>\n      <td class=\"voice\">Packets</td>\n      <td class=\"sms\">Encrypted, framed bits</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">6. Radio</td>\n      <td class=\"voice\">Electromagnetic waves</td>\n      <td class=\"sms\">1,800 MHz signal in the air</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">7. Fiber backbone</td>\n      <td class=\"voice\">Photons</td>\n      <td class=\"sms\">Light pulses in glass</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">8. His phone</td>\n      <td class=\"voice\">All of the above, reversed</td>\n      <td class=\"sms\">Sound in his ear</td>\n    </tr>\n  </tbody>\n</table>\n\nTotal elapsed time from your lips to his ear: **about 150–250 milliseconds**.\n\nThe remarkable thing is how *real-time* this is. Every layer must keep up with every other layer. \nIf the codec falls behind, the audio buffers underrun and you hear gaps. If the modem misses a transmission slot, packets get lost. If the network adds too much latency, the conversation feels awkward and you start talking over each other. The whole stack runs in lockstep, continuously, for the duration of the call.\n\n### Example 2: Texting Chennai\n\nNow let's do the same trip with a text message: you type **\"Hello\"** in the Messages app and send it to **+91 98765 43210**. \nSame destination, same person. But everything below the surface is different.\n\n#### Layer 1: Physics, your finger on a key\nYou press the \"4\" key on the keypad to start typing. \nThis physically closes a contact, allowing electrons to flow through the closed circuit.\nNo sound. No microphone. Just a switch closing.\n\n#### Layer 2: Components, keypad matrix scan\n\nThe Unisoc T107 is constantly scanning the keypad matrix, driving voltage onto rows and reading columns. When you press \"4,\" the chip detects voltage on the row/column intersection that corresponds to that key. A GPIO interrupt fires. The chip records: *key code for \"4\" pressed.*\n\n#### Layer 3: Digital logic, input event\n\nThe keypad driver writes the keycode (`0x34` for ASCII \"4\") into a register. An interrupt handler in the firmware picks it up and places it into the kernel's input event queue. In text-mode T9 input, the \"4\" key represents the letters \"g, h, i.\" Pressing \"4\" twice means \"h.\" A short keypress sequence (4-3-5-5-5-6) becomes the word \"Hello.\" The keystroke history is buffered. The Messages app maintains a string in RAM. After your final keypress, the string in memory contains the five characters: H, e, l, l, o.\n\n#### Layer 4: CPU and the application\n\nThe Messages app runs on top of Series 30+ on the CPU. When you press \"Send,\" the app:\n\n1. Reads the destination number from the input field (`+91 98765 43210`)\n2. Reads the message body from its string buffer (`\"Hello\"`)\n3. Packages them into an **SMS PDU (Protocol Data Unit)** — a structured byte sequence defined in the GSM standard (3GPP TS 23.040)\n4. Hands the PDU to the modem via an internal API\n\nAn SMS PDU has a precise format. \nFor \"Hello\" sent to +91 98765 43210, the bytes look something like:\n\n```\n07 91 21 43 65 87 09 F2 11 00 0B 91 98 76 54 32 10 F0 00 00 05 48 65 6C 6C 6F\n```\n\nThat's the entire message: protocol header, recipient number (in a packed format called *semi-octets*, where digit pairs are nibble-swapped), message length, encoding flag, and the five characters of \"Hello\" in their ASCII bytes (`48 65 6C 6C 6F`).\n\nThe total: 26 bytes. The whole text message is **208 bits**.\n\n#### Layer 5: The modem and the radio path\n\nHere's where the SMS path *diverges* from the voice path in an important way.\nA voice call requires a **dedicated channel** — your phone is allocated a continuous slot of radio time for the duration of the call. SMS, by contrast, hitches a ride on the **signaling channel** — the same low-bandwidth control channel that the network uses for paging messages, registration, and tower handoffs.\n\nThe SMS PDU is small enough to fit in a few signaling messages. The modem:\n\n1. Wraps the PDU in a **CP-DATA** message (Control Plane Data, the SMS-specific signaling protocol)\n2. Encrypts it\n3. Transmits it during the next signaling slot\n\nThis happens in a single brief radio burst — maybe 100 milliseconds total of radio activity — and then the radio goes back to sleep. \nThere's no continuous stream like voice. SMS is a *fire and forget* burst. This is also why SMS works in places voice doesn't. If signal is so weak that voice would drop out, SMS might still get through, because the signaling channel is more aggressively error-corrected and a single retry is cheap.\n\n#### Layer 6: The SMSC, a fundamental difference from voice\n\nYour text doesn't go directly to your friend's phone. \nIt first goes to a **Short Message Service Center (SMSC)**, a server inside your carrier's network whose job is to *store and forward* SMS messages.\n\nThis is the most important difference between SMS and voice:\n\n- **Voice** is a **live circuit**. If your friend's phone is off, the call fails.\n- **SMS** is **store and forward**. If your friend's phone is off, the SMSC holds the message and tries to deliver it later.\n\nThe SMSC accepts your \"Hello,\" acknowledges receipt to your phone (this is what triggers the \"delivered\" confirmation), and queues the message for delivery to Airtel's network in India.\n\n#### Layer 7: The journey across the world\n\nThe SMS travels from your carrier's SMSC to Airtel's SMSC via international signaling links. Historically these used a protocol called **SS7** (Signaling System 7), the same system that handles call setup, roaming, and number lookups across the global telephone network. Modern networks increasingly use **Diameter** (the IP-based replacement) and various IP-based interconnects. Either way, the payload is *tiny* compared to a voice stream. A voice call sends ~12 kbps continuously for minutes. An SMS sends 26 bytes once. The infrastructure cost of an SMS is, almost literally, nothing.\n\nThe undersea cable journey is the same as before, packets flow through fiber, hop through routers, arrive in Mumbai or Chennai. Total travel time: a few hundred milliseconds.\n\n#### Layer 8: Delivery to your friend's phone\n\nAirtel's SMSC receives the message and looks up subscriber `+91 98765 43210`. \n\nTwo cases:\n\n**If his phone is online:** Airtel's SMSC sends a paging message to the cell tower his phone last registered with. The tower paging message says: *\"Phone 98765-43210, you have an SMS waiting.\"* His phone, listening to the signaling channel during its periodic wake-ups, hears its ID and acknowledges. The SMSC then transmits the actual PDU to the phone over the same signaling channel.\n\n**If his phone is offline:** the SMSC holds the message. When his phone next registers with the network (for example, when he turns it back on), the SMSC delivers the queued messages.\n\n#### Layer 9: His phone reconstructs the text\n\nHis Nokia 3210 receives the PDU, decrypts it, and hands it to the SMS subsystem. The SMS subsystem:\n\n1. Parses the PDU header to extract sender, timestamp, and encoding\n2. Decodes the payload bytes (`48 65 6C 6C 6F`) back into the characters H, e, l, l, o\n3. Stores the message in the phone's SMS database (in flash memory)\n4. Triggers a notification — the screen lights up, a tone plays, the inbox icon updates\n5. The Messages app, when opened, fetches the message from the database and renders it on the LCD\n\nHe sees \"Hello\" on his screen.\n\n![Whole journey from Bottom up view](/images/mobilephone/wholejourney.png){fig-alt=\"The whole journey from bottom up view.\"}\n\n#### The whole journey\n\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Layer</th>\n      <th class=\"voice\">What's moving</th>\n      <th class=\"sms\">Form</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\">1. Finger</td>\n      <td class=\"voice\">Mechanical force</td>\n      <td class=\"sms\">Two metal contacts touching</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">2. Keypad matrix</td>\n      <td class=\"voice\">Voltage</td>\n      <td class=\"sms\">Row/column scan</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">3. Input event</td>\n      <td class=\"voice\">Bits</td>\n      <td class=\"sms\">Keycode in a register</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">4. App + OS</td>\n      <td class=\"voice\">String in memory</td>\n      <td class=\"sms\">\"Hello\" as 5 ASCII bytes</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">5. Modem</td>\n      <td class=\"voice\">SMS PDU</td>\n      <td class=\"sms\">26 bytes wrapped in signaling protocol</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">6. Signaling channel</td>\n      <td class=\"voice\">Radio burst</td>\n      <td class=\"sms\">~100 ms of transmission, then silence</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">7. SMSC</td>\n      <td class=\"voice\">Stored message</td>\n      <td class=\"sms\">Queued in carrier's server</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">8. Network hop</td>\n      <td class=\"voice\">SS7 / Diameter packets</td>\n      <td class=\"sms\">Light pulses in undersea fiber</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">9. His phone</td>\n      <td class=\"voice\">All of the above, reversed</td>\n      <td class=\"sms\">Text rendered on LCD</td>\n    </tr>\n  </tbody>\n</table>\n\nTotal time from your \"send\" tap to his screen lighting up: **typically 1–5 seconds**, sometimes longer if the SMSC is busy or his phone is briefly offline.\n\n### Comparing the two journeys\n\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Aspect</th>\n      <th class=\"voice\">Voice call</th>\n      <th class=\"sms\">SMS</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\">Real-time?</td>\n      <td class=\"voice\">Yes, continuous</td>\n      <td class=\"sms\">No, bursty</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">Bandwidth</td>\n      <td class=\"voice\">~12 kbps continuous</td>\n      <td class=\"sms\">208 bits, once</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">Radio active</td>\n      <td class=\"voice\">For entire call</td>\n      <td class=\"sms\">~100 ms total</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">Network resource</td>\n      <td class=\"voice\">Dedicated voice channel</td>\n      <td class=\"sms\">Signaling channel</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">If recipient is offline</td>\n      <td class=\"voice\">Call fails</td>\n      <td class=\"sms\">Stored and delivered later</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">Latency tolerance</td>\n      <td class=\"voice\">Must be under ~300 ms</td>\n      <td class=\"sms\">Can take seconds or minutes</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">Encoding</td>\n      <td class=\"voice\">AMR voice codec</td>\n      <td class=\"sms\">ASCII / GSM 7-bit</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">Power cost on phone</td>\n      <td class=\"voice\">High — radio at full power</td>\n      <td class=\"sms\">Tiny — one short burst</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\">Per-message cost to carrier</td>\n      <td class=\"voice\">Significant (continuous bandwidth)</td>\n      <td class=\"sms\">Nearly zero</td>\n    </tr>\n  </tbody>\n</table>\n\n## Protocol Stack View\n\nSo far, we saw the phone from the bottom up: sound becomes voltage, voltage becomes bits, bits become radio waves, and radio waves enter the cellular network.\n\nNow we need a second view: the **protocol stack view**.\n\nA protocol stack explains the rules followed by each layer. The phone is not simply throwing bits into the air. Every message is formatted, timed, corrected, encrypted, routed, and decoded.\n\n::: {.stack-flow}\n## General Communication Flow\n\n<div class=\"flow-step\"><strong>1. Human action</strong><span>You speak, type, tap, or request something.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>2. Application request</strong><span>The dialer, messages app, or browser creates a request.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>3. Service protocol</strong><span>The phone decides whether this is voice, SMS, or internet data.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>4. Encoding</strong><span>Speech, text, or data is converted into digital form.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>5. Authentication and encryption</strong><span>The SIM and network verify identity and secure the transmission.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>6. Radio control</strong><span>The modem manages tower connection, timing, and channel use.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>7. Reliable bit transfer</strong><span>The data is framed, checked, corrected, and retransmitted if needed.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>8. Physical radio waves</strong><span>The RF hardware turns bits into electromagnetic waves.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>9. Carrier network</strong><span>The tower and carrier core route the information.</span></div>\n<div class=\"flow-arrow\">↓</div>\n\n<div class=\"flow-step\"><strong>10. Destination device or server</strong><span>The other phone or internet server receives and responds.</span></div>\n:::\n\nThe same phone can make a voice call, send an SMS, or open a website. These feel different to the user, but all of them pass through layered systems.\n\n::: {.three-card-grid}\n\n::: {.tech-card}\n### Voice Call\n\n**Type:** Real-time stream  \n**Delay tolerance:** Very low  \n**Network behavior:** Live connection  \n**Main network node:** Switching center or IMS  \n**If receiver is offline:** Call fails  \n**Power use:** High during call  \n\nA voice call must keep moving continuously. If packets arrive too late, the conversation feels broken.\n:::\n\n::: {.tech-card}\n### SMS\n\n**Type:** Short stored message  \n**Delay tolerance:** Seconds or minutes are acceptable  \n**Network behavior:** Store and forward  \n**Main network node:** SMSC  \n**If receiver is offline:** Message waits  \n**Power use:** Low, short radio burst  \n\nSMS is not a live conversation. The carrier can store the message and deliver it later.\n:::\n\n::: {.tech-card}\n### Internet Data\n\n**Type:** Packet-based data  \n**Delay tolerance:** Depends on the app  \n**Network behavior:** Request and response  \n**Main network node:** Packet core  \n**If receiver/server is unavailable:** Request fails or retries  \n**Power use:** Variable  \n\nInternet data breaks information into packets. Web pages, apps, and videos all use this packet-based model.\n:::\n\n:::\n\nThe important lesson is that the phone is a layered communication machine. The user sees a simple action, but underneath it the device performs encoding, authentication, radio scheduling, error correction, routing, and decoding.\n\n## Engineering Views\n\nWe understand the phone as a system: it has hardware, software, radio, protocols, a SIM identity, and a carrier network behind it.\nBut to understand a mobile phone more deeply, we need a few more engineering views.\n\nIt is a collection of specialized subsystems.\n\n```text\nUser interface\n   ↓\nApplication processor or phone firmware\n   ↓\nBaseband processor / modem\n   ↓\nRF transceiver\n   ↓\nPower amplifier, filters, antenna switch\n   ↓\nAntenna\n   ↓\nCell tower\n```\n\n**Signal path:**\n\nVoice / SMS / data → modem → radio → antenna → tower\n\n**Control path:**\n\nSIM identity → authentication → tower selection → timing → power control → handover\n\n**RF Front End View:**\n\nBaseband bits\n   ↓\nRF transceiver\n   ↓\nFilter\n   ↓\nPower amplifier\n   ↓\nAntenna switch\n   ↓\nAntenna\n   ↓\nRadio waves\n\nOn the receiving end, the path is reversed:\n\nRadio waves\n   ↓\nAntenna\n   ↓\nAntenna switch\n   ↓\nLow-noise amplifier\n   ↓\nFilter\n   ↓\nRF transceiver\n   ↓\nBaseband processor\n\n\n**Network Generation View:**\n\n\n2G / GSM  → voice and SMS were central\n3G        → better data and mobile internet\n4G / LTE  → packet-based internet architecture\nVoLTE     → voice becomes IP-based voice\n5G        → higher speed, lower latency, more flexible network design\n\n## Frequency Bands and Duplexing\n\nWe said the phone transmits at 1,800 MHz, but skipped a real problem: during a call, the phone transmits and receives **simultaneously**. If both used the same frequency, the phone's 200 mW transmitter would drown out the microwatt signal from the tower, like hearing a whisper while shouting.\n\nTwo solutions:\n\n<table class=\"comparison-table\">\n  <thead>\n    <tr>\n      <th class=\"aspect\">Method</th>\n      <th class=\"voice\">How it works</th>\n      <th class=\"sms\">Used in</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td class=\"aspect\"><strong>FDD</strong> (Frequency Division Duplex)</td>\n      <td class=\"voice\">Transmit and receive on different frequencies, simultaneously. Typically 45–95 MHz apart.</td>\n      <td class=\"sms\">GSM, most LTE</td>\n    </tr>\n    <tr>\n      <td class=\"aspect\"><strong>TDD</strong> (Time Division Duplex)</td>\n      <td class=\"voice\">One frequency, taking turns in time slots.</td>\n      <td class=\"sms\">Many 5G bands, Wi-Fi</td>\n    </tr>\n  </tbody>\n</table>\n\nThis is why phones list paired frequencies per band. **LTE Band 3** uses 1,710–1,785 MHz uplink and 1,805–1,880 MHz downlink. The 95 MHz gap lets a **duplexer** (a sharp filter) isolate the two directions — and it's why we'll see separate filters per band on the PCB.\n\n## The Clock: TCXO\n\nCellular networks run on time slots. LTE requires timing accurate to about **0.1 microseconds**. A regular quartz crystal drifts with temperature, a phone in a hot car versus a cold pocket would lose its slot.\n\nThe fix is a **TCXO** (Temperature-Compensated Crystal Oscillator): a quartz crystal with a small circuit that measures temperature and corrects frequency in real time, holding accuracy to about **0.5 parts per million**.\n\nOn the PCB, the TCXO is a small metal-cased component near the modem. Without it, time-division multiplexing, the mechanism that lets millions of phones share spectrum, falls apart.\n\n## Power Path and the PMIC\n\nA phone runs on one battery cell at **3.7 V**. But the chips inside need many voltages:\n\n- Application processor cores: ~**0.8 V**\n- Modem: ~**1.1 V**\n- Memory: **1.2 V** or **1.8 V**\n- Display backlight: **5–20 V**\n- RF power amplifier: ~**3.4 V** during transmit bursts\n- SIM card: **1.8 V** or **3 V**\n\nGenerating all of these efficiently from one battery is the job of the **PMIC** (Power Management Integrated Circuit), typically the second-largest chip on the PCB after the main processor. It contains a dozen or more switching and linear regulators, and handles:\n\n- **Battery charging** managing current and voltage across charge phases\n- **Battery monitoring** tracking voltage, current, and temperature to estimate capacity\n- **Power sequencing** turning rails on and off in the right order at boot and shutdown\n- **Sleep states** shutting down rails the phone doesn't need when idle\n\nGood battery life largely means a well-designed PMIC and software that knows when to tell it to shut things off. \n\n## Conclusion\n\nA mobile phone looks simple from the outside, but internally it is a layered communication machine. A voice call begins as pressure waves in air, becomes voltage, becomes digital samples, becomes compressed packets, becomes radio waves, becomes light pulses in fiber, and finally becomes sound again in another person’s ear. SMS follows a different path. It is not a live stream, but a short stored message that travels through signaling channels and SMS centers.\n\nThe important lesson is that a phone is a combination of computing, radio engineering, signal processing, power management, software, cryptography, and telecom infrastructure.\n\nIn the future post, I will move from the system-level explanation to the physical device itself. I will use a Nokia-style feature phone teardown to identify the battery, PCB, processor, modem, PMIC, RF front end, antenna, keypad, display, speaker, microphone, SIM interface, and other subsystems.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}